### ISSUE TITLE
Spline 0.5.3 not working with aws glue

### ISSUE THREAD

**Issue by jnshubham** [AbsaOSS/spline-spark-agent#101]
I am trying to run glue job with the spline dependency but it is failing with this error, it seems there are multiple bindings which are causing the issue.

![image](https://user-images.githubusercontent.com/43238222/85830492-5107a400-b7aa-11ea-8996-755d57f15bf9.png)

Can you please provide a way or show me the correct way to implement lineage in glue jobs.

I am passing the conf parameters as 

```
 --conf "spark.sql.queryExecutionListeners=za.co.absa.spline.harvester.listener.SplineQueryExecutionListener" \
  --conf "spark.spline.producer.url=http://REDACTED/producer"
```

The code to initialize the spark session is 
```
from pyspark.context import SparkContext
from awsglue.context import GlueContext
spark = GlueContext(SparkContext()).spark_session
```

**Comment by cerveada** [comment]
Wrong Scala versions, probably. Try to google the exception >
https://stackoverflow.com/questions/56007488/exception-in-thread-main-java-lang-nosuchmethoderror-scala-predef-refarrayop

**Comment by jnshubham** [comment]
The job works fine if I don't provide the admin jar.

So possibly a class is responsible for the conflict.

And we cannot control the versions of scala in glue, so if possible can this be fixed so that we can incorporate this with glue jobs also?

**Comment by cerveada** [comment]
How do you provide the Spline jar? And which one exactly? Spline admin is only for initializing database if you want to capture lineage you have to use Spline agent.

**Comment by jnshubham** [comment]
Thanks for quick reply..
My bad I was using the wrong jar but after using the spline agent jar My job succeded but still no lineage is generated so I checked the logs and found the error as spline agent is not able to connect.

And failed due to connection refused error.

I am running the rest server and web api on an EC2 instance and given the EC2 ip as the producer to the glue job.

If anyone can help me understand if it is possible to connect to EC2 from glue jobs or not.

Because if it is not possible then we cannot generate the lineage for glue jobs

**Comment by cerveada** [comment]
This seems to be AWS issue. I never used glue, so I cannot help you with that. Make sure the producer url is correct and that the connection is not blocked by AWS firewall rules.

**Comment by jnshubham** [comment]
Thanks a lot.
I resolved it as my VPC was blocking the traffic
