### ISSUE TITLE
Pluggable handling of arbitrary relations

### ISSUE THREAD

**Issue by schaloner-kbc** [AbsaOSS/spline-spark-agent#104]
At the moment, only hard-coded relations (XMLRelation, JDBCRelation, etc) are handled by the agent.

It would be nice to have support for a pluggble mechanism that allows arbitrary relations to be handled as an extension mechanism.  

I've already made the changes, and will attach a pull request immediately.

**Comment by wajda** [comment]
@schaloner-kbc
Hi Steve, we've introduced a new Plugin API that is intended to make handling 3rd party relations even easier. Could you please check if it works for your case? See [README#plugins](/AbsaOSS/spline-spark-agent/blob/release/0.5/README.md#plugins)
