### ISSUE TITLE
Support for SaveAsTable and SQL (Azure Databricks)

### ISSUE THREAD

**Issue by mithun1979** [AbsaOSS/spline-spark-agent#107]
Hi, 

I was testing out Spline (0.4). Its  a great tool. Thanks for sharing the tool.

It seems Spline 0.4 does not have support for SaveAsTable, or SQL Statements such as 
INSERT OVERWRITE...., CREATE TABLE TAB1 USING DELTA LOCATION "/mnt/..." AS SELECT ....LOCATION, which are dependent 
of schema catalog.

Just wanted to check if these features are available in any of the higher versions of Spline, that I can try out.

Thanks and Regards
Saurav Chakraborty

**Comment by wajda** [comment]
What Spark version are you using?

**Comment by wajda** [comment]
Most common SQL operations are supported (those that you mentioned should be). Please check https://github.com/AbsaOSS/spline-spark-agent README

**Comment by mithun1979** [comment]
Hi Wajda, 
Thanks for the prompt response.
I am using Spark 2.4.5 in Azure Databricks,  along with Spline 0.4.2 (spark_agent_bundle_2_4_0_4_2.jar). 
I will have a look at the link.


Just wanted the mention my observations thus far for reference. 
For normal load and save operations, I am able to see the lineage. For instance, the following shows the lineage in the UI tool:

val rawdata = spark.sql("select * from rawtable")
rawdata.write.format("delta").mode("overwrite").save("/mydestinationpath_adls_gen2")


However, it seems operations like the following, are not showing lineage and not pushing data to arangodb.

(a) val rawdata = spark.sql("select * from rawtable")
rawdata.write.format("delta").mode("overwrite").option("path","/mydestinationpath_adls_gen2").saveAsTable("mytable")

(b) 
%sql
CREATE TABLE mytable
USING DELTA
LOCATION  "/mydestinationpath_adls_gen2"
AS 
SELECT * FROM rawtable

Thanks and Regards
Saurav Chakraborty

**Comment by mithun1979** [comment]
I upgraded the Spark fat jar  dependency to spark-2.4-spline-agent-bundle_2.11-0.5.3, as per the documentation in the link. Its seems that the behavior is still the same, as mentioned above.
I am still using the 0.4.2 versions for the rest service war and ui war files in this test.

Thanks and Regards
Saurav Chakraborty

**Comment by wajda** [comment]
Isn't it the same as #40?

**Comment by mithun1979** [comment]
Yes. Seems to be the same. Thanks for reference.
Regards
Saurav Chakraborty

**Comment by cerveada** [comment]
Hi @mithun1979 I just tested both examples from you (a and b) and both seems to be working fine. Could you make sure you are using the latest Agent version (0.5.3) and test again?

**Comment by mithun1979** [comment]
Hi @cerveada ,
Thanks for the update. I will test and confirm.
Thanks and Regards
Saurav Chakraborty

**Comment by mithun1979** [comment]
Hi @cerveada ,

I tested with the latest version of the agent jar downloaded from - https://search.maven.org/search?q=a:spark-2.4-spline-agent-bundle_2.11.
It seems I am still getting the same issue. Should I refer to some other location.


PS: I am still using 0.4.2 versions for the rest service war and ui war files in this test.
Thanks and Regards
Saurav Chakraborty

**Comment by cerveada** [comment]
This is strange. I have Scala 2.11 Spark 2.4.5 and Delta 0.3.0 (and also tested with 0.6.1) and it works. 
Which version of delta do you have?

**Comment by mithun1979** [comment]
I am using Delta Lake 0.5.0 on Databricks Runtime 6.5 ( Spark 2.4.5, Scala 2.11).

Thanks and Regards
Saurav Chakraborty

**Comment by mithun1979** [comment]
I

**Comment by mithun1979** [comment]
I will try on a lower version of Databricks runtime and provide an update.

Thanks and Regards
Saurav Chakraborty

**Comment by cerveada** [comment]
I tried Delta 0.5.0 and still works.

- Do you have any errors or warnings in log of agent or spline gateway?
- You could try to update gateway and UI to the latest version as well. (It should work with gateway 0.4, but to be sure error is not there)
- Could you provide a runnable piece of code that is failing for you? Best would be with some dummy data.

**Comment by mithun1979** [comment]
Ok...Thanks. I will get back with updates.
Regards
Saurav Chakraborty

**Comment by mithun1979** [comment]
Please find the sample code I tried below. with inline comments.

import org.apache.spark.sql.types._

case class Employee(id: Int, name: String)
val (emp1,emp2) = (Employee(1,"Harry"),Employee(2,"Ron"))
val empList = Seq(emp1, emp2)
//Creating sample dataframe
val dfEmp = empList.toDF()

/*Scenario 1: Writing Dataframe to delta path
Result: Successfully shows up in Spline UI.
*/
dfEmp.write.format("delta").mode("overwrite").save("/mnt/powerbi/splinetest")

/*Scenario 2: Saving Dataframe as externally managed Delta table
Result: Fails to Register in Spline UI
*/
dfEmp.write.format("delta").mode("overwrite").option("path","/mnt/powerbi/splinetest1").saveAsTable("unit_test.splinetest_table1")

/*Scenario 3: Creating new delta table using DDL by copying data from existing delta table.
Result: Fails to Register in Spline UI
*/
spark.sql("""DROP TABLE IF EXISTS unit_test.splinetest_table2""") 
dbutils.fs.rm("/mnt/powerbi/splinetest2",true)
spark.sql("""
CREATE TABLE unit_test.splinetest_table2
USING DELTA
LOCATION  "/mnt/powerbi/splinetest2"
AS 
SELECT * FROM unit_test.splinetest_table1
""")

Please also find attached the corresponding Spline UI screenshot attached. I have tested this twice. The first two rows in the screenshot correspond to the scenario -  Saving files in delta format to a path. 
The UI is not capturing the actions for saveAsTable or CREATE TABLE DDL.


![SplineUI_Screenshot](https://user-images.githubusercontent.com/1445286/89108556-2539a700-d457-11ea-814b-64753be80b28.png)

Thanks and Regards
Saurav Chakraborty

**Comment by mithun1979** [comment]
I don't see any errors in Spark Driver Logs. Noticed in the gateway Tomcat access logs, for scenario one mentioned above, entries in the following format get registered:
"POST /rest-gateway-0.4.2/producer/execution-plans HTTP/1.1" 201 49
"POST /rest-gateway-0.4.2/producer/execution-events HTTP/1.1" 201 -

However, for scenario 2 and scenario 3, there are no such entries.

**Comment by mithun1979** [comment]
I will test with the updated UI and Gateway versions and provide further updates.

**Comment by cerveada** [comment]
> "POST /rest-gateway-0.4.2/producer/execution-plans HTTP/1.1" 201 49
> "POST /rest-gateway-0.4.2/producer/execution-events HTTP/1.1" 201 -

Yes, these two POSTs should appear for each lineage captured. That's the agent sending lineage data to gateway.

**Comment by cerveada** [comment]
The only remaining difference seems to be that you run Databricks Spark On Azure. I run the spark only locally. I will try to test it on Azure.

**Comment by cerveada** [comment]
If you could test the same code locally instead of on Azure, that would also help us to narrow down the issue.

**Comment by mithun1979** [comment]
Ok..Thanks. Currently, I am not using a local version of Spark. I will  setup, test and provide an update.

**Comment by mithun1979** [comment]
Hi @cerveada ,

Would it be ok if  I  try to set up a databricks workspace with relevant dependencies on Azure and add you as a user. 
That way, we we can have a look at the same compute engine.

Thanks and Regards
Saurav Chakraborty

**Comment by cerveada** [comment]
Yes that would be great, I'm not sure what you need to add me, but this is my account on azure: Adam.Cervenka@absa.africa

I requested access to databricks on Azure, but it takes some time to set it up, so I haven't test anything yet.

**Comment by mithun1979** [comment]
Ok....Great. I have tried to add you as a guest user. You might have received an email on Adam.Cervenka@absa.africa for registering. Once you have registered, I can add you to Databricks account.

Thanks and Regards
Saurav Chakraborty

**Comment by cerveada** [comment]
I am registered.

**Comment by mithun1979** [comment]
Ok..Thanks for the confirmation. I have added you in Databricks.  Could you please try accessing the notebook URL to confirm the connectivity. 
Kindly let me know in case you have any issues.

Thanks and Regards
Saurav Chakraborty

**Comment by cerveada** [comment]
I'm able to access the notebook, I found the logs and there are few logs from Spline, but not many. Could we configure the logger to log everything under `za.co.absa.spline` using TRACE? That would give as much more information. It will be also good to log more than just the class name, so we can easily find logs for spline.

Spline is using the same logging as Spark. So the configuration should be done in the same place, but I don't really know where is it in Azure.

It's log4j. I can prepare the config file if you want.

**Comment by mithun1979** [comment]
Ok...I will configure the log4j for the driver and confirm. 

Thanks and Regards
Saurav Chakraborty

**Comment by mithun1979** [comment]
I have configured the logging.Please find attached the log for reference.
[stdout.spline.txt](https://github.com/AbsaOSS/spline-spark-agent/files/5030734/stdout.spline.txt)

**Comment by wajda** [comment]
`class com.databricks.sql.transaction.tahoe.commands.CreateDeltaTableCommand was not recognized as a write-command`
Looks like a cause.

**Comment by cerveada** [comment]
It seems to be some close source code. Closest one I found is `org.apache.spark.sql.delta.commands.CreateDeltaTableCommand` I'm not sure why that one is not used.

Anyway I will prepare an agent package that will log more info about that command. That should help us to extract the lineage. It's not ideal, but It looks like we have any other option.

**Comment by wajda** [comment]
Just an idea - we could add an option to an agent that would enable automatic reflective inspection of selected commands (or all unrecognized commands), and dump that info to a disk (later maybe even to the server). That package could then be used to easily implement a corresponding plugin. That way adding support for proprietary environments would be greatly simplified.

**Comment by cerveada** [comment]
@mithun1979 I found out it's not that easy to get that debug log for generic object, but it seems to be mostly working now. If you can try to use the jar in this message, it should log more info about the data source.

I have to zip it because github doesn't allow me to upload jars here.
[spark-2.4-spline-agent-bundle_2.11-0.6.0-SNAPSHOT.jar.zip](https://github.com/AbsaOSS/spline-spark-agent/files/5041496/spark-2.4-spline-agent-bundle_2.11-0.6.0-SNAPSHOT.jar.zip)

Hopefully this will be enough for us to implement the source extractor, but if not I can improve that loging to get even more info. I will probably do it anyway for future uses.

**Comment by mithun1979** [comment]
Ok..Thanks. I will try out and provide and update.

Thanks and Regards
Saurav Chakraborty

**Comment by mithun1979** [comment]
Please find attached the updated logs after using the latest jar.
[stdout.spline.txt](https://github.com/AbsaOSS/spline-spark-agent/files/5041855/stdout.spline.txt)

Thanks and Regards
Saurav Chakraborty

**Comment by cerveada** [comment]
That looks like it could be enough. I will go trough it in more detail on Monday and I will try to implement the extractor.

**Comment by cerveada** [comment]
Please try this new version. It should hopefully recognize the write.

[spark-2.4-spline-agent-bundle_2.11-0.6.0-SNAPSHOT.jar.zip](https://github.com/AbsaOSS/spline-spark-agent/files/5057062/spark-2.4-spline-agent-bundle_2.11-0.6.0-SNAPSHOT.jar.zip)

**Comment by mithun1979** [comment]
Ok..Thanks. I will try and provide an update.

Thanks and Regards
Saurav Chakraborty

**Comment by mithun1979** [comment]
Works Great. I am able to see the lineage now. Thanks a ton for your help. Including screenshot for reference.
[
![Screenshot](https://user-images.githubusercontent.com/1445286/89987822-46db2f80-dc9c-11ea-8a47-b71bc97edc8d.png)
](url)

Thanks and Regards
Saurav Chakraborty

**Comment by cerveada** [comment]
That's great! Would you mind also checking the read source in the lineage? We would like to be able to process both read and write using the DataBricks delta. It should have correct url and DatasourceType.

**Comment by mithun1979** [comment]
Sure...Here is the Lineage with source for Scenario 2 with saveAsTable, where we are reading from dataframe and writing to delta.

![SaveAsTable](https://user-images.githubusercontent.com/1445286/90000642-0edce800-dcae-11ea-81ac-3c4c7367cec1.png)

**Comment by mithun1979** [comment]
Here is the Lineage with source for Scenario 3 with CREATE TABLE AS , where we are reading from delta table and creating 
another delta table.

![Create Table](https://user-images.githubusercontent.com/1445286/90000832-464b9480-dcae-11ea-8545-efb853c5b9ed.png)

**Comment by cerveada** [comment]
That seems to be correct. Thanks for your help with this issue. The fix will be part of the next release. Let us know if you found any other issues.

**Comment by mithun1979** [comment]
Sure. Thanks for your cooperation.
 
Thanks and Regards
Saurav Chakraborty

**Comment by mithun1979** [comment]
Just to be on the same page, Should I close this issue or would  you want to keep this open for tracking/reference for the next release.
Thanks and Regards
Saurav Chakraborty

**Comment by cerveada** [comment]
Let's keep it open. Thanks

**Comment by mithun1979** [comment]
Ok..Thanks!
Regards
Saurav Chakraborty

**Comment by mithun1979** [comment]
Just had an additional query. 
Are there any plans to support Spark 3, Scala 2.12 in near future.

Thanks and Regards
Saurav Chakraborty

**Comment by cerveada** [comment]
Scala 2.12 is supported already. Spark 3 support is planned, but I don't know when it will happen. Problem is mostly libraries incompatibilities.

**Comment by mithun1979** [comment]
Ok....Thanks!
Regards
Saurav Chakraborty
