### ISSUE TITLE
Spline not tracking lineage for destinations that are prefixed with protocols

### ISSUE THREAD

**Issue by sreeraaman** [AbsaOSS/spline-spark-agent#111]
Hi,

I have a dataframe. I do some aggregations and write it out to Azure ADLS Gen2. See code below.

import org.apache.spark.sql.functions._
val aggregate = df.groupBy("YEAR_ID").agg(sum("SALES").as("YTD"))
aggregate.write.format("parquet").mode("append").save("abfss://xx@yy.dfs.core.windows.net/enriched/SalesAggregate")

However, if I have a mount point created and save using the following command, it tracks the lineage and is visible in the UI. 

aggregate.write.format("parquet").mode("append").save("/mnt/adls/enriched/SalesAggregate")

I am using Spline 0.5.3 on databricks.

Thanks

**Comment by cerveada** [comment]
Hello,
could you please set logger to log everything under za.co.absa.spline using TRACE and send as the log?

**Comment by sreeraaman** [comment]
All,
Sorry for the confusion. I had forgotten to set the producer url via spark conf / system property.  It is working now. Sorry for the confusion.
Thanks

**Comment by boje** [comment]
@cerveada what maven you have installed and your system.property. I have hard time getting this to working to a custom rest server from Databricks.

**Comment by wajda** [comment]
```
Apache Maven 3.6.3 (Red Hat 3.6.3-5)
Maven home: /usr/share/maven
Java version: 1.8.0_275, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-6.fc33.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.9.16-200.fc33.x86_64", arch: "amd64", family: "unix"
```
