### ISSUE TITLE
Explicitly capturing lineage for provided SQL

### ISSUE THREAD

**Issue by pratapmmmec** [AbsaOSS/spline-spark-agent#123]
## Background 
Our workloads are mix of Spark and Hive. Spline is great in capturing Spark lineage but end lineage breaks the moment we have a Hive job (SQL). 

## Question
Is there a way to provide an API which accepts SQL ("Spark compatible") in spark-agent or even an end point in rest-gateway and harvests and capture lineage out of that SQL. I do understand that it will require an explicit call by application instead of being event based but will give teams some way to capture end to end lineage for mixed workloads (Hive + Spark)

**Comment by wajda** [comment]
A short answer is yes, although not super easy but doable.
But before going into capturing a custom lineage let me ask you what Hive SQL are you executing that isn't captured automatically? Spline agent is supposed to support Hive queries out of the box.

**Comment by pratapmmmec** [comment]
We have Hive on Tez. I am not sure if spline can capture lineage for such workloads. If we have some plugin etc, I would be happy to explore or take that route.

**Comment by cerveada** [comment]
Could you please configure the logger to log everything under za.co.absa.spline using TRACE and send us the log? 

If the lineage wasn't captured but an event was trigged by Spark it should appear in the log.

**Comment by pratapmmmec** [comment]
May be I wasn't clear in first place. When I say Hive SQL, they run via Hive on Tez and not via spark-submit & nor Hive on Spark which means that we don't have any spark session. Its purely a hive process and not spark.

That's why I was checking if we have a way to capture lineage explicitly for SQLs which are Spark or Hive compatible.

**Comment by wajda** [comment]
Ah, Ok, that makes sense. Spline has a so called _Producer REST API_ which is used to record lineage data. It's used by Spline Spark Agent, but it's designed to be generic. You can call this API to record Hive lineage manually, or you may develop a specific Hive Agent to do it in a similar way Spark Agent does it.
https://opensource.bigusdatus.com/spline/rest/docs/producer.html

Basically you need to make two calls:
1. `POST /execution-plans` - to register your execution plan that consists of at minimum a _Write_ operation and one or more _Read_ operations.
2. `POST /execution-events` - to register the fact of execution of the given execution plan.

It is enough to have the lineage recorded. You can see the examples here - https://github.com/AbsaOSS/spline-spark-agent/tree/develop/examples/src/main/shell

Please note that the current Spline UI implementation depends on the some Spark specific internal structure of the execution plans. So even though _Producer API_ allows you to register _any_ arbitrary execution plan it might not be displayed correctly in the Spline UI. This is a temporary limitation of Spline UI and _Consumer API_ and will be resolved in Spline 0.6
