### ISSUE TITLE
Computation of log messages shouldn't occur unless the respected logging level is enabled

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#135]
E.g. `ObjectStructureDumper` is kicked even though TRACE level is disabled.

Also check other logging statements.

**Comment by cerveada** [comment]
Maybe, we could use this: https://github.com/lightbend/scala-logging

**Comment by wajda** [comment]
I was thinking about [slf4s](http://slf4s.org/) that we already have in the classpath. At the first glance both libs look identical to me. Is there any substantial difference?

**Comment by cerveada** [comment]
Not sure but scala-logging's repo seems to be more active slf4s seems to be dead (last commit was in 2017), but there is a fork timo-schmid/slf4s.

**Comment by wajda** [comment]
Just realized that the Spark logger that we are currently using is actually `slf4j` logger that supports lazy logging as well.

**Comment by wajda** [comment]
I've forgot that there is no pass-by reference in Java. and `Logger.trace(...)` arguments are still passed by value. So all SLF4J laziness boils down to a lazy `.toString()` call, nothing more. Instead `spark.Logging` extra methods should be called to achieve true laziness.

**Comment by cerveada** [comment]
Yeah, I missed that too. Typically, in Java it would be done using lambda expressions.
