### ISSUE TITLE
Capture SparkSession.config

### ISSUE THREAD

**Issue by liangjun-jiang** [AbsaOSS/spline-spark-agent#140]
This is a feature request.  
In our Spark application, we use SparkSession's config feature to add custom metadata fields. 
For example, we define 
```
SparkSession sparkSession = SparkSession.builder().appName("Example 3")
                .config("application_owner", "johnDoe")
                .config("code_repo", "https://https://github.com/AbsaOSS/spline-spark-agent")
                .getOrCreate();
```
In Spline agent, we want those custom metadata, `("application_owner", "johnDoe")` and `("code_repo", "https://https://github.com/AbsaOSS/spline-spark-agent")` to be tracked in the `extraInfo` of Spline, as such

```
"extraInfo": {
        "appName": "Example 3",
        "config": {
              "application_owner": "johnDoe",
             "code_repo": "https://https://github.com/AbsaOSS/spline-spark-agent"
        }, 
        "dataTypes": [
```

**Comment by wajda** [comment]
Closing in favor of #169
See https://github.com/AbsaOSS/spline-spark-agent/pull/141#issuecomment-774074920
