### ISSUE TITLE
Question about documentation: Use spline in your application

### ISSUE THREAD

**Issue by liangjun-jiang** [AbsaOSS/spline-spark-agent#142]
I am reading the documentation: https://absaoss.github.io/spline/ 
The portion of `Use Spline in your application`, the documentation says
>You also need to set some configuration properties. Spline combines these properties from several sources:
> Hadoop config (core-site.xml)
> JVM system properties
> spline.properties file in the classpath

I could understand the `spline.properties file in the classpath`, but what do I need to do with `Hadoop config (core-site.xml)` and `JVM system properties`? how and what and why do I need to set them?

Thanks

**Comment by cerveada** [comment]
Spline is searching for the properties in all these sources. This is to make your life easier. You just need to set the properties once in any source that is most convenient for you.

So if you specify the properties in `spline.properties file in the classpath`. You don't need to do it anywhere else.

**Comment by wajda** [comment]
A little clarification - it only concerns the Spline settings, how they are resolved. It doesn't affect Spark or anything else in any way.
Also mind the precedence. The values set in Hadoop config have the highest precedence while `spline.properties` has the lowest one.
