### ISSUE TITLE
Guidance on Atlas Integration

### ISSUE THREAD

**Issue by nevi-me** [AbsaOSS/spline-spark-agent#143]
Hi, I understand the reasons why Spline 0.5 doesn't support Atlas, so I'm not asking about that.

We are trying out an Atlas implementation, and as part of that, we've found ourselves with no good source for lineage.
I understand that the Spline Spark agent communicates with Spline via API, so we're thinking of hooking into that in order to send lineage data to Atlas instead.

Is there guidance on how I could do this? I've been reading the README, and my understanding's that the plugin API is for integrating 3rd party sources.
I'd probably try to do this in Kotlin as I have less experience with Scala, but I can still use Scala if using another JVM language would be a barrier.

Thanks

**Comment by wajda** [comment]
Plugin API is for extending/customizing the lineage harvesting from the Spark execution plan. If you only need to send your lineage data to another endpoint the easiest way is to create your own implementation of the `LineageDispatcher` interface and register it via `spline.lineage_dispatcher.className` config property.

E.g.
```scala
package foo.bar

import org.apache.commons.configuration.Configuration
import za.co.absa.spline.harvester.dispatcher.LineageDispatcher
import za.co.absa.spline.producer.model._

class MyLineageDispatcher(conf: Configuration) extends LineageDispatcher  {
  
  override def send(plan: ExecutionPlan): String = ... // return UUID encoded as a quoted string, including double quotes

  override def send(event: ExecutionEvent): Unit = ...
  ...
}
```

Then register it in the config property:
```
spline.lineage_dispatcher.className=foo.bar.MyLineageDispatcherDecorator
```

**Comment by nevi-me** [comment]
Thanks Alex, I'm currently going through the process, looks like it'll work with Kotlin. 
I'm creating a stub that implements `LineageDispatcher` and returns errors on the `send()`s; so I can see what the output looks like

**Comment by jbadeau** [comment]
Hello, did u ever manage integrate with atlas using the agent

**Comment by nevi-me** [comment]
@jbadeau no, I had bigger issues with Atlas at the time, so I abandoned the work. I was making slow progress though, so it should be feasible.

What I would recommend is to do the integration using Scala. I used Kotlin out of familiarity, and I was hitting compatibility issues between things like Kotlin lists vs Scala iterables.
