### ISSUE TITLE
LineageDispatcher: method `send(execPlan)` should return UUID

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#144]
For the sake of consistency `LineageDispatcher.send(plan: ExecutionPlan)` method should return the type of `ExecutionPlan.id` property. Currently it's expected to return a double-quoted string which is confusing.

**Comment by cerveada** [comment]
Type of `ExecutionPlan.id` is `Option[UUID]`, but the send method should return just`UUID`, right?

**Comment by cerveada** [comment]
Yes
