### ISSUE TITLE
[Question] Working with Spring Boot Application

### ISSUE THREAD

**Issue by liangjun-jiang** [AbsaOSS/spline-spark-agent#147]
Our spring boot application integrates with Spark feature, Can Spline agent work directly with a Spring Boot application in the codeless way?

```
./bin/spark-submit \
  --packages za.co.absa.spline.agent.spark:spark-2.4-spline-agent-bundle_2.11:0.5.4 \
  --conf "spark.sql.queryExecutionListeners=za.co.absa.spline.harvester.listener.SplineQueryExecutionListener" \
  --conf "spark.spline.producer.url=http://localhost:3000/producer" \
    --class com.example.MY-SPRING-BOOT-SPARK-App \
    spring-boot-demo-spark-application-1.0-SNAPSHOT.jar
```

**Comment by wajda** [comment]
In a codeless mode Spline agent is initialized by Spark by instantiating a listener. Unless I'm missing something the Spring Boot should not interfere with this process. So yes, I think it should work in Spring boot.

**Comment by liangjun-jiang** [comment]
I have setup a sample spring boot application. the codeless way does work. Thanks
