### ISSUE TITLE
generate DDL as part of Execution Plan

### ISSUE THREAD

**Issue by liangjun-jiang** [AbsaOSS/spline-spark-agent#148]
not sure whether DDL is already included in the Execution Plan, from what I have experimented, I have not seen it. 
From I read, the following commands are implemented, what would be the outcomes of those commands? I assume it should be some kind of DDL? 
```
CreateDataSourceTableAsSelectCommand (org.apache.spark.sql.execution.command)
CreateHiveTableAsSelectCommand (org.apache.spark.sql.hive.execution)
CreateTableCommand (org.apache.spark.sql.execution.command)
```

as
```
CREATE TABLE hive_test.department(
    department_id int ,
    department_name string
``

**Comment by wajda** [comment]
The SQL syntax is translated into a Spark execution plan long before Spline kicks in. So what you get back is actual operations that Spark executed, not the original DSL. Unfortunately AFAIK there is no way to recreate the original DSL from the execution plan in Spark. Theoretically an equivalent DSL can be created, but that kind of functionality is not in the scope of Spline, and I doubt it will ever be. Nothing stops you, however, from trying to do it yourself using the info generated by Spline agent.

**Comment by liangjun-jiang** [comment]
Sure. So when Spline says it has implemented `CreateDataSourceTableAsSelectCommand` etc, what does it exactly mean?

**Comment by wajda** [comment]
It means that the execution plan is captured from that command.
