### ISSUE TITLE
Documentation: Add a configuration guide

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#154]
Explain the following:
- How to configure Spline Spark agent
- What properties are available for the `DefaultSplineConfigurer`
- How and when to use a custom configurer
- How to extend `LineageDispatcher` or how to decorate `HttpLineageDispatcher`
- How to capture extra user metadata
- anything else that might be relevant

**Comment by wajda** [comment]
@Zejnilovic

**Comment by azurele** [comment]
Hi, It would be great if the documentation could cover how to use Spline on Databricks too. Current documentation doesn't elaborate how to setup Spline with Databricks clusters, particularly Spline UI. Thanks!

**Comment by wajda** [comment]
Noted. Thanks.

**Comment by cerveada** [comment]
I think we need special pages for agent, gateway and UI on https://absaoss.github.io/spline/, so we can put artifact specific documentation there. The current page should still stay and have guide how to run everything together and general Spline overview.

**Comment by wajda** [comment]
> Hi, It would be great if the documentation could cover how to use Spline on Databricks too. Current documentation doesn't elaborate how to setup Spline with Databricks clusters, particularly Spline UI. Thanks!

It will be covered in AbsaOSS/spline-getting-started#5
