### ISSUE TITLE
Add nootebook url from Databricks to custom API (build in Azure Function)

### ISSUE THREAD

**Issue by boje** [AbsaOSS/spline-spark-agent#162]
On the Databricks cluster `za.co.absa.spline.agent.spark:spark-2.4-spline-agent-bundle_2.11:0.5.3` in installed with exclusions of org.json4s:json4s-ext_2.11:${json4s.version}
Cluster is running 6.4 (includes Apache Spark 2.4.5, Scala 2.11)

With the code below, nothing happens and no errors. If `spline.mode` is set to `REQUIRED` then a error in showed then initialise spark.enableLinegeaTracking()
`za.co.absa.spline.harvester.exception.SplineInitializationException: Spark Agent was not able to establish connection to Spline Gateway. HTTP Response: 404 `

**Test code**
```
%scala
System.setProperty("spark.sql.queryExecutionListeners", "za.co.absa.spline.harvester.listener.SplineQueryExecutionListener")
System.setProperty("spline.producer.url","https://xxxxx.azurewebsites.net/api/func/producer")

import za.co.absa.spline.harvester.SparkLineageInitializer._
spark.enableLineageTracking()
```

```
%python
rawData = spark.read.option("inferSchema", "true").json("/databricks-datasets/structured-streaming/events/").limit(10)
rawData.createOrReplaceTempView("rawData")
sql("select r1.action, count(*) as actionCount from rawData as r1 join rawData as r2 on r1.action = r2.action group by r1.action limit 10").write.mode('overwrite').csv("/tmp/pyaggaction.csv")
```

**Working with older spark agent version**
If I install za.co.absa.spline:spark-agent-bundle-2.4:0.4.2 then the code is working fine and sending information to API. But I am to see how to pass custom variables as the nookbook url from the older version.

**Comment by cerveada** [comment]
There is a check for `HEAD producer/status` that is trying to make sure the gateway is alive. You will have to add this to your API.

You can see the 0.5 producer API here:
https://github.com/AbsaOSS/spline/tree/release/0.5/producer-rest-core/src/main/scala/za/co/absa/spline/producer/rest/controller

**Comment by boje** [comment]
Thanks.. It is working now with spark-2.4-spline-agent-bundle_2.11:0.5.3.
The core issue from my situation, is that the API need to revice PUT request-
