### ISSUE TITLE
HDFS lineage dumper

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#174]
A port of https://github.com/AbsaOSS/spline/tree/release/0.3.9/persistence/hdfs/src/main/scala/za/co/absa/spline/persistence/hdfs

A lineage dispatcher implementation that simply offloads the lineage data into an HDFS. The location of the lineage file is relative to the target data file.

Only HDFS writes to be supported by this dispatcher.

**Comment by wajda** [comment]
@benedeki @Zejnilovic @aaishaosman

**Comment by lokm01** [comment]
@dk1844 think we can contribute S3 support for this dispatcher?

**Comment by wajda** [comment]
Sure, please go ahead.

**Comment by wajda** [comment]
Done.
Please note that this implementation is basically just a port of the aforementioned impl from Spline 0.3.9 that is being used in Enceladus at the moment. It is by no means a generic implementation, is based on a number of assumptions about a particular use case (i.e. data is written to HDFS, no concurrent writes. no appends supported).
