### ISSUE TITLE
Rename synthetic attributes of a union operation to match original attribute name

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#221]
In the following example
```scala
val df1 = Seq((1, 2, 3)).toDF()
val df2 = Seq((4, 5, 6)).toDF()
val df3 = df1.union(df2)
```
`df3` schema consists of attributes `_1, _2, _3`, while Spline reports different attribute names:

![image](https://user-images.githubusercontent.com/795479/117713108-83a96800-b1d5-11eb-9325-7ed8db5f9bbd.png)

Even though it might seem logical from the technical perspective to reflect the true nature of the resulted attributes, introducing new attribute names into the execution plan will likely be confusing to the user. Especially in cases with more unions...

```scala
val df1 = Seq((1, 2, 3)).toDF()
val df2 = Seq((4, 5, 6)).toDF()

val df3 = df1.union(df2).filter('_1 > 0)
val df4 = df1.union(df2).filter('_2 < 0)

val df5 = df3.union(df4)
```

![image](https://user-images.githubusercontent.com/795479/117714823-c66c3f80-b1d7-11eb-99ca-bec0ce9ac256.png)

While in fact the resulted attributes are still just `_1`, `_2` and `_3`

**Comment by wajda** [comment]
@cerveada

**Comment by cerveada** [comment]
It's not ideal either way. But at least the users still can see that the attributes are not the same by highlighting them.

**Comment by wajda** [comment]
I'd follow the least astonishment principle and preserve/mimic the Spark representation where possible.
The spark union operation emits the attributes from the 1st dataset. So even though we emit new attributes we at least should name them accordingly.
