### ISSUE TITLE
Make Spark 3.1 and Scala 2.12 a default profile for dev and tests

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#240]

**Comment by cerveada** [comment]
There is a downside to this. It's really easy to write code that works in 2.12, but not in 2.11. But not vice versa.

**Comment by wajda** [comment]
As discussed, closing it as "won't fix" due to cross building issues. The best we can do is to stick with Spark 2.4 (as the only Spark version that supports both Scala 2.11 and 2.12) unless we drop support for Spark 2.x series.
