### ISSUE TITLE
Spark-spline-agent 0.6.0-SNAPSHOT significant memory footprint on the Spark driver

### ISSUE THREAD

**Issue by elisabetao** [AbsaOSS/spline-spark-agent#269]
Hello, 

We noticed while using Spark-spline-agent 0.6.0-SNAPSHOT that it had a memory significant footprint of over 1G on the Spark driver. We would like to deploy the Spline agent harvester on an existing system that already have preconfigured application driver and executor memory configuration, but if enabling the Spline agent on top, the applications require driver memory increase, else they seem to fail.

Has anyone else reported such issues? Is there work being done in this sense?

Thank you very much

**Comment by wajda** [comment]
Hi @elisabetao, thanks for reporting this.
Can you give us more details on your setup?
What lineage dispatcher are you using, how complex is your Spark job (sharing the Spark job source code would be ideal).

**Comment by elisabetao** [comment]
Hi Alex,

Thanks for the quick reply. I have tried the HTTP dispatcher and Kafka dispatcher and if I do not increase the driverMemory to 2GB (from the default 1GB), this basic insert fails  and container gets killed in yarn due to the fact that the container is running beyond the 'PHYSICAL' memory limit, no matter the dispatcher.
```
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark.sql("INSERT INTO airports_test VALUES ('OTP','Bucharest Henri Coanda International Airport','Bucharest','BUC','ROM','44.5707','26.0844')")
```
Thanks in advance

**Comment by wajda** [comment]
I cannot reproduce it. Spline agent is a lightweight library that processes the executed Spark plan and sends it over the dispatcher. So unless your Spark job is crazy complex (producing exec plans with thousands of operations and complex expressions) the footprint of the agent should hardly be noticeable. Can you please use some profiler and get more insight on your memory dump?
I would suspect there is something else in the process that eats up memory.

**Comment by elisabetao** [comment]
I ran some profiling but I couldn't find anything specific, however what I noticed is that without spline certain basic  queries can run with a driver of 512m, while with spark-spline-agent enabled  it requires 1700m and more. 
On your side, are you able to use the lineage with default Spark memory driver of 1g?

Thanks a lot

**Comment by wajda** [comment]
Are you talking about heap or non-heap memory?
I've tested with `spark-shell --driver-memory 512m` and it works with no issues at all.

Below is a memory monitoring screenshot for a continuous run of about 1000 jobs (with Spline tracking) in a client mode on my local PC.

![image](https://user-images.githubusercontent.com/795479/128779279-f7807863-48e6-4f62-a68d-6fe3c746ab12.png)

**Comment by wajda** [comment]
and this is without Spline - pure Spark

![image](https://user-images.githubusercontent.com/795479/128781350-337eae48-8851-4198-b4ed-51f54d07e796.png)

As you can see the difference is negligible.

**Comment by wajda** [comment]
I've also tried running Spline examples in a Docker container with RAM limit of 1200mb and it worked. But this is a memory limit for the entire container including OS and Maven (Spark examples are run by Maven inside the container).

I would say that 512m heap size is the absolute minimum for a Spark driver alone to be able to run. Plus a couple of hundred mb of non-heap space, plus every additional library in the classpath obviously requires extra memory... Of course there might be some room for improvement, but given that Java is memory intensive in general, I wouldn't give Spark driver container less than about 1.5gb RAM. It's a fare amount to me.
