### ISSUE TITLE
Google BigQuery Plugin

### ISSUE THREAD

**Issue by mohanajuhi166** [AbsaOSS/spline-spark-agent#277]
We have a requirement to add google Bigquery support  as part of the Plugin API support: https://github.com/AbsaOSS/spline-spark-agent#plugins.

Is there a possibility for this to be added as a feature?
I have did some development on my own as well regarding Bigquery.

Thanks & Regards.

**Comment by wajda** [comment]
Sure, why not.
I would recommend you to create a plugin first, make it working on your side, and then create a PR when it's ready. Please also write some integration tests. 
Thank you.

**Comment by mohanajuhi166** [comment]
Thank you @wajda ,
was working on the plugin and noticed that JDBCPlugin may work in this case for bigquery.
An example below:-
`spark.sqlContext.read.format("jdbc").option("url", "jdbc:googlebigquery:DataSetId=MyDataSetId;ProjectId=MyProjectId;").option("dbtable","Orders").option("driver","cdata.jdbc.googlebigquery.GoogleBigQueryDriver").load()`

Any thoughts on the same? Thank you.

**Comment by wajda** [comment]
> Any thoughts on the same? Thank you.

I have nothing to add. If it works it works :)

**Comment by mohanajuhi166** [comment]
PR raised : https://github.com/AbsaOSS/spline-spark-agent/pull/292

**Comment by mohanajuhi166** [comment]
Raised a PR @wajda . I am not entirely sure what kind of integration tests i can write for bigquery.

**Comment by wajda** [comment]
Can we create a test account and use Google free tier for automated testing purposes?
