### ISSUE TITLE
Support for `InsertIntoTable` node

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#287]
similar to #286

**Comment by cerveada** [comment]
There is no `InsertIntoTable` command in Spark or Delta. So I am not really sure what this issue is about?

Sql like: `INSERT INTO aaa VALUES ('a925eaf2-e342-497b-85fb-773e81bf57f5')` into DSV2 table will actually generate `AppendData` command.

**Comment by wajda** [comment]
It's not a `Command`, it's a `LogicalPlan` and just like `AppendData` it also has a `query` field. And because `AppendData` not being a command still appears in the top of the execution plan I thought that maybe there is a similar case for the `InsertIntoTable`.

**Comment by wajda** [comment]
Well I just figured that the doc says the `InsertIntoTable` only exists in unresolved plans. So I suppose we can safely ignore it.

```
/**
 * Insert some data into a table. Note that this plan is unresolved and has to be replaced by the
 * concrete implementations during analysis.
 *
 * @param table the logical plan representing the table. In the future this should be a
 *              [[org.apache.spark.sql.catalyst.catalog.CatalogTable]] once we converge Hive tables
 *              and data source tables.
```

**Comment by cerveada** [comment]
It was removed in Spark 3: https://github.com/apache/spark/pull/25763.

That and the fact that GitHub doesn't allow searching anywhere else than in HEAD explains why I was not able to find it.
