### ISSUE TITLE
Problems with spark-3.0-spline-agent-bundle_2.12:0.6.2

### ISSUE THREAD

**Issue by mpindado** [AbsaOSS/spline-spark-agent#302]
Hi, so I just need to attach the agent into a spark-shell and print out the data into a console.
My configuration is a local spark-shell running in ubuntu:

Spark 3.0.1, scala 2.12.10.

First I tried this:

```
spark-shell \
  --packages za.co.absa.spline.agent.spark:spark-3.0-spline-agent-bundle_2.12:0.6.2 \
  --conf "spark.sql.queryExecutionListeners=za.co.absa.spline.harvester.listener.SplineQueryExecutionListener" \
  --conf "spark.spline.lineageDispatcher=console"

```
This fails because it cannot find these libraries (maybe a firewall issue?):
```
                :: commons-collections#commons-collections;3.2.1!commons-collections.jar
                :: commons-logging#commons-logging;1.1.1!commons-logging.jar
```
So I cloned the repo and generated the bundle myself:
**spark-3.0-spline-agent-bundle_2.12-0.6.2.jar**

I start this way:

```
spark-shell \
  --driver-class-path spark-3.0-spline-agent-bundle_2.12-0.6.2.jar \
  --jars spark-3.0-spline-agent-bundle_2.12-0.6.2.jar \
  --conf "spark.sql.queryExecutionListeners=za.co.absa.spline.harvester.listener.SplineQueryExecutionListener" \
  --conf "spark.spline.lineageDispatcher=console"

```
And do a simply:
`val df = Seq(1,2,3).toDF("id")
`
I get multiple exceptions:

Sometimes:

**java.lang.NoClassDefFoundError: Could not initialize class za.co.absa.spline.harvester.plugin.registry.AutoDiscoveryPluginRegistry$**

other times:
**io.github.classgraph.ClassGraphException: Uncaught exception during scan
Caused by: java.lang.UnsupportedOperationException: newFileChannel**

Any clue to this problem?

Best regards

**Comment by wajda** [comment]
What JVM are you using?

**Comment by mpindado** [comment]
Very good point....I am using JRE openJDK 11 for starting the spark-shell, and compiled the bundle with adopt JDK 11, although I see a setting in scala-maven-plugin to use 1.8 for target.

Should I compile the bundle and run the shell with 1.8?

**Comment by wajda** [comment]
Yes, please use 1.8

**Comment by mpindado** [comment]
That was it, although spark 3 runs on jdk11, switching my local spark-shell to run over JDK8 made the same jar work without problems.

Thank you so much, nice work.

**Comment by wajda** [comment]
#309 should fix the issue.
Compilation still requires Java 1.8, but runtime can be any Java version supported but Spark.
