### ISSUE TITLE
Capture failed executions

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#32]
If a job fails we should still send an execution plan and the error to the server.
Failed events should be filtered out in the query when building a lineage across jobs.

**Comment by ASchwad** [comment]
I will just drop this here for discussion / implementation notice:
Within an AWS Glue Job execution (Spark 2.4; Scala 2.11), the method `onSuccess` in `QueryExecutionEventHandler.scala` is called correctly, but if the execution fails `onFailure` is not called. I experience the same behaviour, when i try to run a PysparkShell locally. For testing this behaviour, I have inserted a log.info(...) for both methods within the spline-agent code. 

According to the [spark docs](https://spark.apache.org/docs/2.2.1/api/java/org/apache/spark/sql/util/QueryExecutionListener.html) this should work, but it seems like the environments mitigate the handling of these failures.

**Comment by ASchwad** [comment]
https://github.com/apache/spark/pull/27904
> If java.lang.Error is thrown during the execution, QueryExecutionListener doesn't get notified right now.

This seems to explain the problem

**Comment by cerveada** [comment]
Thanks for info. The first Spark version including this fix is `Spark 2.4.6`

**Comment by wajda** [comment]
Wow, that's interesting. The PR is merged in Spark 2.4, but I kinda disagree with that.
`java.lang.Error` should normally never be caught, as it usually indicates a problem with the JVM itself (Like OOM, thread dead etc). Unless I misunderstand something Spark `QueryExecutionListener.onFailure()` is designed to deal with the _query execution failures_, not JVM failures. Also, the method signature contains an `Exception` argument, not `Throwable`. The impact to the application developers now will be that `NonFatal()` extractor will not work, so they will have to explicitly unwrap the given exception and examine the cause for proper error handling. IMO, this implementation is very controversial.

**Comment by wajda** [comment]
I'd suggest that we make the failed execution handling configurable, e.g.:
```properties
spline.sql.failure.capture=NONE | NON_FATAL | ALL
```
Basically we could use an approach similar to [NonFatalQueryExecutionListenerAdapter](https://github.com/AbsaOSS/commons/blob/abf9a75a15e4ced49df9153a9fd72259a04dbf64/src/main/scala/za/co/absa/commons/spark/NonFatalQueryExecutionListenerAdapter.scala) to handle _fatal_ and _non-fatal_ events separately.

**Comment by zacayd** [comment]
@ASchwad - did you have any experience with Aws Glue with spline?
if yes- i will be glad to learn how
