### ISSUE TITLE
Logging: Spline init errors in BEST_EFFORT mode should be logged as WARN

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#326]
![image](https://user-images.githubusercontent.com/795479/137408241-4df53896-773b-474a-b5e6-9242f53d51e8.png)

**Comment by cerveada** [comment]
I am not sure the log severity should change depending on the mode. 

As a user I might use some log analysing tool and see there are 0 errors and some warnings from spline agent => Ok that means agent works, right?

It should be quite easy to filter out spline logs from the rest of spark logs if you really don't care about the agent.

**Comment by wajda** [comment]
After giving it a second thought I agree with you. The log severity should indeed be chosen from the Spline perspective, not from the hosting app perspective.
Closing the ticket.
