### ISSUE TITLE
make log level independent on spline mode

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/spline-spark-agent#330]
We already established we don't want the log levels to differ depending on the spline mode. 
The rest of the agent logs should behave this way as well.

**Comment by cerveada** [comment]
I just noticed that there is a different behaviour when lineage recognition fails. When in required mode, the exception is thrown only to be captured a few levels higher and just logged anyway.

We should think about what the mode should actually do and if it should be just for initialization or do more.

**Comment by wajda** [comment]
The main purpose of the mode is to control a) if Spline should be activated at all, and if yes then b)  if the failure of lineage tracking should interrupt the main Spark job.

In other words, it's less related to the error logging, but rather to the error handing and initialization.

**Comment by cerveada** [comment]
Let's discuss this tomorrow.

**Comment by cerveada** [comment]
After discussion, we agreed that SplineMode should matter only during initialization of the agent.
When errors happen when agent is capturing a lineage it will be caught and logged (independent on a mode) and the agent will continue processing any following lineages.
