### ISSUE TITLE
Should Spline capture Hive Warehouse Connector activity

### ISSUE THREAD

**Issue by dwarry** [AbsaOSS/spline-spark-agent#34]
## Background
The old HiveContext etc. classes have been deprecated since Spark 2.0, in favour of the new [Hive Warehouse Connector](https://docs.cloudera.com/HDPDocuments/HDP3/HDP-3.1.4/integrating-hive/content/hive_hivewarehouseconnector_for_handling_apache_spark_data.html), which seems to be necessary to interact with LLAP. 

## Question
Should Spline be capturing lineage operations performed through the HWC? At the moment it doesn't seem to. 

I put together a [minimal example](https://github.com/dwarry/sactest/tree/spline)  which has a PySpark job that just reads from a csv file into a dataframe and then saves that as a json file, and into a Hive table. The Spline lineage only shows the data being written to the json file.  

```python
from pyspark.sql import SparkSession
from pyspark_llap import HiveWarehouseSession
import pyspark.sql.types as T


spark = SparkSession.builder.appName("SAC-Test").enableHiveSupport().getOrCreate()

sc = spark.sparkContext

sc._jvm.za.co.absa.spline.harvester \
    .SparkLineageInitializer.enableLineageTracking(spark._jsparkSession)


hive = HiveWarehouseSession.session(spark).build()

hive.setDatabase("sactest")

schema = T.StructType()
schema.add(T.StructField("col1", T.IntegerType(), False))
schema.add(T.StructField("col2", T.StringType(), False))
schema.add(T.StructField("col3", T.DateType(), False))

df = spark.read.csv("/tmp/test_data.csv", schema, header=True, quote="'")

df.write.format(HiveWarehouseSession.HIVE_WAREHOUSE_CONNECTOR).mode("append").option("table", "sac_test").save()

df.write.json("/tmp/spline_test.json", "overwrite")
```

which is launched by

```bash
hdfs dfs -put -f test_data.csv /tmp

HWC_JAR=local:/usr/hdp/current/hive_warehouse_connector/hive-warehouse-connector-assembly-1.0.0.3.1.4.0-315.jar 
HWC_PY=local:/usr/hdp/current/hive_warehouse_connector/pyspark_hwc-1.0.0.3.1.4.0-315.zip
SPLINE_JAR=/home/mario/spline/spark-agent-bundle-2.3-0.4.1.jar
SPLINE_URL=http://$HOSTNAME:8079/spline-rest-gateway/producer

spark-submit --master yarn \
             --deploy-mode client \
             --jars $HWC_JAR,$SPLINE_JAR \
             --driver-java-options -Dspline.producer.url=$SPLINE_URL \
             --py-files $HWC_PY \
             load_test_data.py
```

The lineage it captures is 

![image](https://user-images.githubusercontent.com/105082/75043980-c1c74880-54b8-11ea-88b7-d09ac26d228e.png)

**Comment by wajda** [comment]
@dwarry ,
Sorry for the long delay. Is this issue still valid?

**Comment by cerveada** [comment]
The Hortonworks Data Platform is already EOL software:
https://endoflife.software/applications/big-data/hortonworks-data-platform-hdp

And new versions are not coming since the company was bought by Cloudera.

**Comment by wajda** [comment]
Ok, So I'm closing the issue as "won't fix". If there is any other or similar issue found that is related to the up-to-date software don't hesitate to let us know.
