### ISSUE TITLE
Support for lineage, transformations on unmanaged table in Azure Databricks

### ISSUE THREAD

**Issue by DhananjayPunekar** [AbsaOSS/spline-spark-agent#351]
Hi, 

I was testing out the latest spline tool. (from here: https://mvnrepository.com/artifact/za.co.absa.spline.agent.spark/spark-3.1-spline-agent-bundle_2.12/0.7.1)

I am using a databricks runtime version 9.1 to work with.

I am not able to track lineage for unmanaged tables in Databricks.
The code I am trying to run on databricks is:

```
val department = spark
  .read
  .option("header",true)
  .csv("abfss://container@zneedc2n14dapsastorage.dfs.core.windows.net/Test_data/department_details/")

val employee = spark
  .read
  .option("header",true)
  .csv("abfss://container@zneedc2n14dapsastorage.dfs.core.windows.net/Test_data/employee_details/Employee_details.csv")

val aggregatedData = employee
.join(department.withColumnRenamed("emp_id","employee_id"),Seq("employee_id"))

aggregatedData
  .coalesce(1)
  .write
  .mode(SaveMode.Overwrite)
  .option("path","abfss://container@zneedc2n14dapsastorage.dfs.core.windows.net/Test_data/agg_emp_data/unmanaged")
  .saveAsTable("adventureworks.Employee_dep_unmanaged")
```

I also saw that there was a similar issue reported earlier #107 
Is the same not carried forward to the latest version?
Or am I doing something wrong?

**Comment by cerveada** [comment]
Hello, could you please set the logger level to `trace` for package `za.co.absa.spline`, run the example again and post the log here?

**Comment by DhananjayPunekar** [comment]
Hi @cerveada ,
Sorry for the delayed response.
This was an issue with my code/version control and not with this library.

Hence closing this issue.
