### ISSUE TITLE
OpenLineage API dispatcher

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#354]
Add a new dispatcher that would send lineage metadata in the [OpenLineage](https://openlineage.io/) format.

OpenLineage JSONSchema:
https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json

**Comment by cerveada** [comment]
- OpenLineage requires two messages, one for start of a run and the other for complete with times of those events. In Spline the times are only in `ExecutionEvent` but we want to also include the lineage from `ExecutionPlan` so the dispatcher will have to combine those two.
- Currently, the dispatcher API is tight to classes defined and generated from Spline producer API. In case of supporting alternative producer API it would make sense to define an internal agent representation of the lineage and then convert to one of JSON representations. An additional benefit would be that a nicer class hierarchy could be created for lineage manipulation inside the agent.
