### ISSUE TITLE
Issue with configuring spline with pyspark

### ISSUE THREAD

**Issue by jakecomp** [AbsaOSS/spline-spark-agent#365]
Hello there, 

I am currently trying to display some lineage on my console with pyspark however I am running into some issues with configuring spline. I am using the spark-spline-agent and I have followed the configuration as shown here:      

![pyspark_problem](https://user-images.githubusercontent.com/44540913/146061801-064f5c62-3324-47ac-b4df-b94ed07fec37.PNG)

When I try running my spark job I get the following error: 

![image](https://user-images.githubusercontent.com/44540913/146062709-6ca7d3e1-d92e-406f-aebf-970d08a23f1a.png)

I think the issue steams from the spark.sql.queryExecutionListeners configuration. I noticed if I use sparl.sql.queryExecutionListener instead of spark.sql.queryExecutionListeners (I removed the s from Listeners)  everything works except I see no lineage on my terminal.  I was just wondering why this is the case and if this has been reported before but from what I can see though nobody has run into this issue.

For context I am using spark version 3.1.2

**Comment by cerveada** [comment]
> I think the issue steams from the spark.sql.queryExecutionListeners configuration. I noticed if I use sparl.sql.queryExecutionListener instead of spark.sql.queryExecutionListeners (I removed the s from Listeners) everything works except I see no lineage on my terminal.

That is because Spark does not know the property without s and will basically ignore it. So Spline is not used at all.
The property is correct.


Since you are using Spline **3.1** you should use `spark-3.1-spline-agent-bundle_2.12` not **3.0**.

Can you try again with the correct bundle?

**Comment by jakecomp** [comment]
Hey @cerveada , 

So I went ahead and tried spark-spline 3.1 bundle and it appears I am running into the same issue. What is interesting is when exactly the error is occurring. It appears that spline tries to initialize but I get the error when I try reading in my csv file.  

The full error message is shown below:  

![image](https://user-images.githubusercontent.com/44540913/146163717-8e964bc4-c575-4d4a-987b-5edc23744565.png)

I have tried reading in my file multiple different ways, all of which produce this same error. I apologize as I am still relatively new to both spark and spline. I don't see the successful spline initialization message so I'm sure it's something I'm doing incorrectly with spline and not how I'm trying to read in my data. 

Thank you again in advance for all your help!

**Comment by wajda** [comment]
This is my log for comparison. Spark 3.1.2, Python 3.10.0. Everything is by default (excepts for turning on the shell INFO logging in log4j.properties).
Everything looks fine, I don't see any errors.

Try to double check your setup.

```
[user1@localhost spark-3.1.2-bin-hadoop3.2]$ bin/pyspark \
  --packages za.co.absa.spline.agent.spark:spark-3.1-spline-agent-bundle_2.12:0.7.1 \
  --conf "spark.sql.queryExecutionListeners=za.co.absa.spline.harvester.listener.SplineQueryExecutionListener" \
  --conf "spark.spline.lineageDispatcher=console"
  
Python 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/user1/Downloads/spark-3.1.2-bin-hadoop3.2/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
:: loading settings :: url = jar:file:/home/user1/Downloads/spark-3.1.2-bin-hadoop3.2/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /home/user1/.ivy2/cache
The jars for the packages stored in: /home/user1/.ivy2/jars
za.co.absa.spline.agent.spark#spark-3.1-spline-agent-bundle_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-eecc14b6-50c3-44b4-bfd4-6db10646847e;1.0
	confs: [default]
	found za.co.absa.spline.agent.spark#spark-3.1-spline-agent-bundle_2.12;0.7.1 in central
	found za.co.absa.spline.agent.spark#agent-core_2.12;0.7.1 in central
	found org.scala-lang#scala-compiler;2.12.14 in local-m2-cache
	found org.scala-lang#scala-reflect;2.12.14 in local-m2-cache
	found org.scala-lang.modules#scala-xml_2.12;1.0.6 in spark-list
	found za.co.absa.commons#commons_2.12;0.1.0 in local-m2-cache
	found org.json4s#json4s-ext_2.12;3.5.3 in local-m2-cache
	found joda-time#joda-time;2.9.5 in local-m2-cache
	found org.joda#joda-convert;1.8.1 in local-m2-cache
	found org.scalaj#scalaj-http_2.12;2.4.1 in local-m2-cache
	found io.github.classgraph#classgraph;4.8.116 in local-m2-cache
	found org.scala-graph#graph-core_2.12;1.12.5 in local-m2-cache
	found com.fasterxml.uuid#java-uuid-generator;4.0.1 in local-m2-cache
	found org.slf4j#slf4j-api;1.7.29 in local-m2-cache
	found commons-configuration#commons-configuration;1.6 in local-m2-cache
	found commons-collections#commons-collections;3.2.1 in local-m2-cache
	found commons-lang#commons-lang;2.6 in local-m2-cache
	found commons-logging#commons-logging;1.1.1 in local-m2-cache
	found commons-digester#commons-digester;1.8 in local-m2-cache
	found commons-beanutils#commons-beanutils;1.7.0 in local-m2-cache
	found commons-beanutils#commons-beanutils-core;1.8.0 in local-m2-cache
:: resolution report :: resolve 448ms :: artifacts dl 11ms
	:: modules in use:
	com.fasterxml.uuid#java-uuid-generator;4.0.1 from local-m2-cache in [default]
	commons-beanutils#commons-beanutils;1.7.0 from local-m2-cache in [default]
	commons-beanutils#commons-beanutils-core;1.8.0 from local-m2-cache in [default]
	commons-collections#commons-collections;3.2.1 from local-m2-cache in [default]
	commons-configuration#commons-configuration;1.6 from local-m2-cache in [default]
	commons-digester#commons-digester;1.8 from local-m2-cache in [default]
	commons-lang#commons-lang;2.6 from local-m2-cache in [default]
	commons-logging#commons-logging;1.1.1 from local-m2-cache in [default]
	io.github.classgraph#classgraph;4.8.116 from local-m2-cache in [default]
	joda-time#joda-time;2.9.5 from local-m2-cache in [default]
	org.joda#joda-convert;1.8.1 from local-m2-cache in [default]
	org.json4s#json4s-ext_2.12;3.5.3 from local-m2-cache in [default]
	org.scala-graph#graph-core_2.12;1.12.5 from local-m2-cache in [default]
	org.scala-lang#scala-compiler;2.12.14 from local-m2-cache in [default]
	org.scala-lang#scala-reflect;2.12.14 from local-m2-cache in [default]
	org.scala-lang.modules#scala-xml_2.12;1.0.6 from spark-list in [default]
	org.scalaj#scalaj-http_2.12;2.4.1 from local-m2-cache in [default]
	org.slf4j#slf4j-api;1.7.29 from local-m2-cache in [default]
	za.co.absa.commons#commons_2.12;0.1.0 from local-m2-cache in [default]
	za.co.absa.spline.agent.spark#agent-core_2.12;0.7.1 from central in [default]
	za.co.absa.spline.agent.spark#spark-3.1-spline-agent-bundle_2.12;0.7.1 from central in [default]
	:: evicted modules:
	commons-logging#commons-logging;1.0.3 by [commons-logging#commons-logging;1.1.1] in [default]
	commons-logging#commons-logging;1.1 by [commons-logging#commons-logging;1.1.1] in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   23  |   0   |   0   |   2   ||   21  |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-eecc14b6-50c3-44b4-bfd4-6db10646847e
	confs: [default]
	0 artifacts copied, 21 already retrieved (0kB/14ms)
21/12/16 12:07:45 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
21/12/16 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
21/12/16 12:07:47 INFO QueryExecutionEventHandlerFactory: Initializing Spline agent...
21/12/16 12:07:47 INFO QueryExecutionEventHandlerFactory: Spline init type: AUTO (codeless)
21/12/16 12:07:47 INFO QueryExecutionEventHandlerFactory: Spline version: 0.7.1 (rev. f5044fa)
21/12/16 12:07:47 INFO QueryExecutionEventHandlerFactory: Spline mode: BEST_EFFORT
21/12/16 12:07:47 INFO DefaultSplineConfigurer: Lineage Dispatcher: console
21/12/16 12:07:47 INFO DefaultSplineConfigurer: Post-Processing Filter: composite
21/12/16 12:07:47 INFO DefaultSplineConfigurer: Ignore-Write Detection Strategy: default
21/12/16 12:07:49 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.AvroPlugin
21/12/16 12:07:49 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.BigQueryPlugin
21/12/16 12:07:49 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.CassandraPlugin
21/12/16 12:07:49 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.CobrixPlugin
21/12/16 12:07:49 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.DataSourceV2Plugin
21/12/16 12:07:49 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.DatabricksPlugin
21/12/16 12:07:49 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.ElasticSearchPlugin
21/12/16 12:07:49 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.ExcelPlugin
21/12/16 12:07:49 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.JDBCPlugin
21/12/16 12:07:49 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.KafkaPlugin
21/12/16 12:07:49 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.MongoPlugin
21/12/16 12:07:49 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.SQLPlugin
21/12/16 12:07:49 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.XMLPlugin
21/12/16 12:07:49 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.composite.LogicalRelationPlugin
21/12/16 12:07:49 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.composite.SaveIntoDataSourceCommandPlugin
21/12/16 12:07:49 INFO QueryExecutionEventHandlerFactory: Spline successfully initialized. Spark Lineage tracking is ENABLED.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 3.1.2
      /_/

Using Python version 3.10.0 (default, Oct  4 2021 00:00:00)
Spark context Web UI available at http://alex-xps:4041
Spark context available as 'sc' (master = local[*], app id = local-1639652866700).
SparkSession available as 'spark'.
>>> 

```

**Comment by cerveada** [comment]
Are you sure it does happen only when using Spline? If you run the same code without 
`--conf "spark.sql.queryExecutionListeners=za.co.absa.spline.harvester.listener.SplineQueryExecutionListener" ` Does it throws the exception?

Could it be this issue:
https://stackoverflow.com/questions/38912879/win7-pyspark-sql-utils-illegalargumentexception

**Comment by jakecomp** [comment]
Hey @wajda and @cerveada, 

I removed --conf "spark.sql.queryExecutionListeners=za.co.absa.spline.harvester.listener.SplineQueryExecutionListener"  and I did not get any errors and my code ran properly (with the exception of no lineage being captured).  

I then also tried the solution mentioned in the link above with regards to adding the sql warehouse and added the sql listener configuration back into my code and I arrive at the same error again. My apologies as this error seems to be a magnet for me. 

For more context I am configuring my spark session in a docker container which then calls my spark job in a python script outside the container. I have tried configuring the spark session purely within the python script with no success as well.  

@wajda I noticed you configured the spark session using pyspark where I am using spark-submit. I'm sure this makes no difference as I have read that the configuration should be the same either way. Below I have included more detailed snippets of the spark configuration in my docker container and the simple spark job I am trying to run in a python script. 

![image](https://user-images.githubusercontent.com/44540913/146464470-7a1a8ddf-1d2f-46a5-8981-b5fe8ceb5414.png)

![image](https://user-images.githubusercontent.com/44540913/146464665-41609c56-59f1-4807-af08-ee067c3f9a86.png)

Thank you both so much for all your help.

**Comment by cerveada** [comment]
I am trying to figure out what is happening. It seems that an exception is thrown during spline initialization, but unfortunately in python no exception details are shown. We know it is `IllegalArgumentException` but no message, no stack trace from JVM. It's hard to find out what is wrong from that.

Also, not sure why is there `: <exception str() failed>`. Maybe exception when processing another exception.

Could you try to add:
```
--conf "spark.sql.pyspark.jvmStacktrace.enabled=true"
```
That should show us the JVM exception as well as the python one, at least I hope.

---

When posting logs and code, please post them as a text rather than screenshots, it will make searching and copying much easier for us. Here is a quick guide how to create code block:
https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by jakecomp** [comment]
@cerveada my apologies, 

This is my first issue I've created so sorry for that! Unfortunately adding `--conf "spark.sql.pypsark.jvmStacktrace.enabled=true"` doesn't show an additional error message. One thing I'm going to explore is try using spline in a juypter notebook.  

Given how the configuration is working for everyone else I'm wondering if the underlying issue is somehow connected to the fact that I am using two containers to run my spark job. I have a container running juypter so perhaps keeping the spark job to a single environment will help?

**Comment by wajda** [comment]
should we close this?

**Comment by Ambarish-29** [comment]
@wajda @cerveada what is the solution for this issue. I am having the same issue. i am using 0.7.0 spline version
