### ISSUE TITLE
Database password is included in execution plans with JDBC data sources

### ISSUE THREAD

**Issue by 97nitt** [AbsaOSS/spline-spark-agent#368]
I was doing some local testing (using v0.7.1 of the agent) to see what execution plans look like for different data sources, standing up a backend that simply logs the requests from the Spline agent. When running a Spark job that reads from a JDBC source, all of the connection parameters were included in the `params` of the read operation, including the password, which should probably be redacted. I didn't test writes, but I'm guessing we'd see the same.

**Comment by wajda** [comment]
There is a `DataSourcePasswordReplacingFilter` that removes sensitive information from the agent output. The filter isn't enabled by default, so you need to enable it explicitly via agent configuration. For example:
```properties
spline.postProcessingFilter.composite.filters=dsPasswordReplace
```
See https://github.com/AbsaOSS/spline-spark-agent/blob/release/0.7.1/core/src/main/resources/spline.default.properties#L104 for details.

I think, we need to enabled it by default in the next major release.
