### ISSUE TITLE
Spark Config :: Arrays properties don't work

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#370]
I'm having trouble getting the composite filter working with two user-defined filters. I'm doing the Spline configuration in my PySpark application, so I have code that now looks like this:
```
        spark = SparkSession \
            .builder \
            .appName(app_name) \
            .config('spark.sql.queryExecutionListeners', 'za.co.absa.spline.harvester.listener.SplineQueryExecutionListener') \
            .config('spark.spline.lineageDispatcher', 'http') \
            .config('spark.spline.lineageDispatcher.http.producer.url', spline_config.url) \
            .config('spark.spline.mode', spline_config.mode.value) \
            .config('spark.spline.postProcessingFilter', 'composite') \
            .config('spark.spline.postProcessingFilter.composite.className', 'za.co.absa.spline.harvester.postprocessing.CompositePostProcessingFilter') \
            .config('spark.spline.postProcessingFilter.composite.filters', 'mcd,password') \
            ... (truncated for brevity)
```
where `password` is the `DataSourcePasswordReplacingFilter`, and `mcd` is another custom filter I've built.

When I run the Spark application the Spline agent initialization fails with:
```
21/12/21 17:32:15 ERROR QueryExecutionEventHandlerFactory: Spline initialization failed! Spark Lineage tracking is DISABLED.
java.util.NoSuchElementException: Missing configuration property spline.postProcessingFilter.mcd,password.className
```
Seems the comma in there isn't serving as a delimiter of filter names. I've tried a few different iterations of spacing around the comma with no effect. Any suggestions on how I can get this working in code instead of a config file?

_Originally posted by @97nitt in https://github.com/AbsaOSS/spline-spark-agent/discussions/369#discussioncomment-1855320_

**Comment by 97nitt** [comment]
Awesome. Thanks for the quick turnaround @wajda!
