### ISSUE TITLE
Add JSON Schema URLs to OpenLineage payloads

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/spline-spark-agent#416]
Create a repository to store immutable schema versions with permanent urls.

Use links to those schemas in open lineage requests.

**Comment by wajda** [comment]
I guess the easiest option would be to create a orphan branch in the `spline` GH repo, named for example `api-doc`, and keep the schema there versioned by the adding the version number suffix to the file name.
The permanent URL to the resource could be, e.g.:
https://raw.githubusercontent.com/AbsaOSS/spline/api-doc/schemas/producer-1.0.json
or via a public CDN (I like this one more):
https://cdn.jsdelivr.net/gh/AbsaOSS/spline@api-doc/schemas/producer-1.0.json
