### ISSUE TITLE
Backport of Spark 3.2 support from 1.0 to 0.7 version series

### ISSUE THREAD

**Issue by karatugo** [AbsaOSS/spline-spark-agent#419]
## Background [Optional]

I am trying to run the getting started guide's TL;DR part. 

Check versions:

```bash
>>> sc._jvm.scala.util.Properties.versionString()
'version 2.12.15'
>>> sc.version
'3.2.1'
```

So, according to the instructions, for Spark version 3.2.1 and Scala version 2.12.15, we need to run the following command.  

```bash
pyspark \
  --packages za.co.absa.spline.agent.spark:spark-3.2-spline-agent-bundle_2.12:0.7.4 \
  --conf "spark.sql.queryExecutionListeners=za.co.absa.spline.harvester.listener.SplineQueryExecutionListener" \
  --conf "spark.spline.producer.url=http://localhost:8080/producer"
```

But this gives the following error. 

<img width="1008" alt="Screen Shot 2022-04-05 at 16 06 23" src="https://user-images.githubusercontent.com/11294823/161761500-6c5dbefb-4a8b-4d4e-b1dd-54462d2639e8.png">

## Question
What is the correct package name for the above command?

**Comment by wajda** [comment]
Support for Spark 3.2 has only been added recently in the version that has not been released yet - 1.0.0
I'll see if I can backport it to 0.7 series and release a quick update
