### ISSUE TITLE
Allow users to extend information that Spline publishes

### ISSUE THREAD

**Issue by d-m-h** [AbsaOSS/spline-spark-agent#449]
All right, in a nutshell:

I'd like to be able to specify as part of my Spark configuration, a class (or classes) that the Spline Agent would pickup and then use to place extra metadata into the payload that it publishes.

Concrete example:

We have more than 1 Hadoop cluster, and we'd like to attach extra metadata to the execution plans that Spline publishes, in order to answer more complex questions like "Do we have column lineage parity across all of our clusters?"

The proposed idea I have is to provide a config that looks like this:

```properties
spark.spline.userMetadataProvider.plugins=com.example.spark.spline.HadoopClusterIdentifierPlugin,com.example.spark.spline.OozieWorkflowMetadataPlugin
```

And then (perhaps) in the `LineageHarvester.scala`, have something like this:

```scala
val planExtra = Map[String, Any](
	ExecutionPlanExtra.AppName -> ctx.session.sparkContext.appName,
	ExecutionPlanExtra.DataTypes -> dataTypeConverter.values,
	ExecutionPlanExtra.UserMetadata -> userMetadataPlugins.map(plugin => plugin.apply(ctx))
)
```

I'd expect the type of `UserMetadata` to be a `Map[PluginIdentifier, Any]`, and the output of the plugin to return a `(PluginIdentifier, Any)` where `type PluginIdentifier = String`.

I'm curious as to what you folks think.

**Comment by cerveada** [comment]
We already have this feature, it's called post processing filters:
https://github.com/AbsaOSS/spline-spark-agent#post-processing-filters

You can implement `PostProcessingFilter` and there just add what information you need. There is a field called extra or extraInfo in lineage objects, that you can use to store and send this information.

There is also `MetadataCollectingFilter` that allows you to just declare what you want to add via json, but that is not in the stable version only in dev branch. See the test as usage example:  [MetadataCollectingFilterSpec.scala](https://github.com/AbsaOSS/spline-spark-agent/blob/develop/core/src/test/scala/za/co/absa/spline/harvester/postprocessing/extra/MetadataCollectingFilterSpec.scala

**Comment by wajda** [comment]
Also see the example - https://github.com/AbsaOSS/spline-getting-started/tree/main/spark-agent-extension-example
