### ISSUE TITLE
Upload AVRO schema

### ISSUE THREAD

**Issue by kylebuckingham** [AbsaOSS/spline-spark-agent#462]
Is there any chance you could add the generated avro schema? I can make one, but I'm not sure what exactly it should by just looking at the result, and I assume you already have it somewhere.

**Comment by cerveada** [comment]
Avro schema for which data? If you mean the lineage that the agent is sending to the server, we don't use Avro for that.

**Comment by kylebuckingham** [comment]
Oh I didn't realize the avro format mentioned was just for what spark was writing/reading. JSON is fine. As a low priority future enhancement, you could add different outputs
