### ISSUE TITLE
Databricks - Spark session stops before spline sends data 

### ISSUE THREAD

**Issue by rinzool** [AbsaOSS/spline-spark-agent#463]
Hi,

I tried to use Spline with databricks job where the cluster is built for the job and directly stopped after. 
I noticed that in that case, the cluster stops directly after the `.write` operation, and too fast, so no data is sent to my API. (If I add some code after, data are sent)

Is there a way to configure spark or spline to _wait_ for `QueryExecutionListener` onSuccess or onFailure method? Or something like that? 
I did not find any solution in `AgentConfig` or in Spark config

Thanks for you help, and thanks for this awesome project!

**Comment by wajda** [comment]
What spark version are you using and how do you _stop_ the cluster?
Normally, when Spark context is shutting down it waits until the event queue is empty.

**Comment by rinzool** [comment]
I use spark 3.2.1 with agent `spark-3-2`
The cluster is automatically shutdown by databricks when the job is over 
Maybe that databricks does not wait that spark context is fully down before closing :thinking: 

I asked databricks about how the cluster is shutting down (to know if it waits for the spark context, or not...)

**Comment by wajda** [comment]
could be... Unfortunately it's not the first time we run into issues when Databricks works differently in some places in comparison to vanilla Spark. But if it's the case there is hardly anything we can do about it on our side I'm afraid.

**Comment by mohitgarg4628** [comment]
Hi @wajda 
I'm facing same issue, not able to capture lineage on databricks job cluster due to cluster shutdown immediately 
Thanks

**Comment by wajda** [comment]
Can you confirm the issue still persists in the latest (1.0.2) agent version and the latest Databricks runtime?

@rinzool 
> I asked databricks about how the cluster is shutting down (to know if it waits for the spark context, or not...)

Did you receive any response from Databricks? Thanks.

**Comment by rinzool** [comment]
Hi @wajda, I did not receive any response from Databricks, but I observed the same thing with other tools (such as OpenLineage)

**Comment by wajda** [comment]
Thanks @rinzool for the feedback. I guess this issue is indeed specific to Databricks runtime and it will be the same for all such tools. So I'm closing the issue as unfixable at this time. Please feel free to re-open it if new info is available in the future.
