### ISSUE TITLE
Generic HTTP Dispatcher

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#472]
As per #469 and #471 when a default HTTP dispatcher is used it tries to handshake with the server assuming there is a Spline server on the other end. This often creates inconvenience for users who are implementing their custom HTTP endpoints.

We need to create a generic HTTP dispatcher that would be functioning similarly to the default HTTP dispatcher or an OpenLineage one , but just would omit handshake and use a latest data model by default.

**Comment by dk1844** [comment]
This was already implemented in the scope of https://github.com/AbsaOSS/spline-spark-agent/issues/482
