### ISSUE TITLE
option to add custom headers for http dispatcher

### ISSUE THREAD

**Issue by ganeshnikumbh** [AbsaOSS/spline-spark-agent#482]
Hi @wajda, @cerveada 

it would be really great if we can provide option (additional http dispatcher properties) to add parameters to http header. In our case (and I am sure for may others), the http endpoint (a Azure function) is secured with api key, which we want to pass through a parameter in http header. 
I know we can always extend the dispatcher code to do this, but the problem is, internally we have to adhere to so many standards and CICD steps (also lack of scala skills), that it is difficult to maintain the entire code and keep it updated at our end.  Please let us know your view on this.

As always, we thank you for this great tool and all your efforts.

**Comment by wajda** [comment]
Yes, I agree, it does make sense. If somebody makes a PR we'll merge it asap. Meantime I put it on a low priority track.

**Comment by rupesh3020** [comment]
@wajda This is really required for our team too. Is it possible for you guys to add this functionality? 

i will try to make a PR for this if there is no plan.

**Comment by wajda** [comment]
@rupesh3020 PR is highly welcomed as we are busy with other stuff. Thank you
