### ISSUE TITLE
Integration with Python

### ISSUE THREAD

**Issue by simran-suri** [AbsaOSS/spline-spark-agent#491]
Hi Team,

I'm trying to create lineage for my pipelines and for it I used sc._jvm.za.co.absa.spline.harvester.SparkLineageInitializer.enableLineageTracking(spark._jsparkSession) above my python code. 

Now, I need to install spark-3.1-spline-agent-bundle_2.12:0.7.8 in my python code repository, to create that lineage. 

Is there any way to install this maven dependency in python code?

**Comment by wajda** [comment]
What exactly do you mean?
The capability of downloading Maven artifacts depends on the tool/platform that you are using, not the programming language.
For example, with the `pyspark` you can do `pyspark --packages za.co.absa.spline.agent.spark:spark-3.1-spline-agent-bundle_2.12:0.7.8` while the Databricks notebook provides a specific UI for installing packages.
