### ISSUE TITLE
Add predefined Azure Functions dispatcher

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#501]
The user should be able to use a predefined lineage dispatcher to send lineage to a custom [Azure Functions](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=in-process%2Cfunctionsv2&pivots=programming-language-csharp#api-key-authorization
) via REST API.

Example:
```properties
spline.lineageDispatcher=azure-functions
spline.lineageDispatcher.azure-functions.header.X-FUNCTIONS-KEY=USER_API_KEY
```

**Comment by cerveada** [comment]
At the end we decided to not create specific dispatcher config for this since it is just one header, but the header config needed was added to readme as part of #482
