### ISSUE TITLE
Add predefined AWS API dispatcher

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#502]
A user should be able to use a predefined dispatcher to call his/her custom AWS REST API.

Example:
```properties
spline.lineageDispatcher=aws-api
spline.lineageDispatcher.aws-api.header....
```

**Comment by cerveada** [comment]
At the end we decided to not create specific dispatcher config for this since it is just one header, but the header config needed was added to readme as part of #482
