### ISSUE TITLE
Not able to authenticate using azure function key as header, returns 401

### ISSUE THREAD

**Issue by rupesh3020** [AbsaOSS/spline-spark-agent#506]
Hi team,

Our team is using the new feature from 0.7.11 where user can give custom headers as spline configuration.
It throws 401 error.
Attaching configuration :
spark.spline.lineageDispatcher http
spark.spline.lineageDispatcher.http.producer.url https://mdc-d-01-azfunc.azurewebsites.net/api/func/TEST
spark.spline.mode REQUIRED
spark.spline.lineageDispatcher.http.header.x-functions-key somekey
spark.databricks.delta.preview.enabled true

logs 👍 
[logs.txt](https://github.com/AbsaOSS/spline-spark-agent/files/9705147/logs.txt)

error on azure function : 
![image](https://user-images.githubusercontent.com/76835566/193800079-78af8172-8a66-43b7-ab0d-f2fd8229c3ec.png)

Can you please help on this?

**Comment by cerveada** [comment]
Hello, this feature is only in development branch and was not released yet.

release 0.7.11 does not include this at all:
https://github.com/AbsaOSS/spline-spark-agent/releases/tag/release%2F0.7.11

**Comment by rupesh3020** [comment]
is it possible to give information on timelines, when it will be part of a release?
Our team is excited to get this feature :)

**Comment by wajda** [comment]
We do not have any precise release schedule, it's ready when it's ready. 
But you are welcome to try the latest build downloaded directly from our CI - https://teamcity.jetbrains.com/project/OpenSourceProjects_AbsaOSS_SplineAgentSpark?mode=builds

Select the latest build from the "develop" branch that corresponds to your Spark and Scala version, and from there click the Artifacts tab.

**Comment by wajda** [comment]
There might be some incomparable changes in the config, but we're happy to assist with that. 
Waiting for you feedback.
