### ISSUE TITLE
Spark 3.* bundles transitively depend on Spark 2.4

### ISSUE THREAD

**Issue by yuribogomolov** [AbsaOSS/spline-spark-agent#515]
The `agent-core` package version is agnostic to the Spark version and it depends on Spark 2.4. In result all Spark 3.* bundles have transitive dependencies on Spark 2.4. See the dependency tree for `spark-3.2-spline-agent-bundle_2.12` below:
````
[INFO] +- za.co.absa.spline.agent.spark:spark-3.2-spline-agent-bundle_2.12:jar:0.7.8:compile
[INFO] |  +- za.co.absa.spline.agent.spark:agent-core_2.12:jar:0.7.8:compile
[INFO] |  |  +- org.apache.spark:spark-core_2.12:jar:2.4.2:compile
```

**Comment by cerveada** [comment]
When the bundles are created profiles are used. So to find out actual dependencies maven should be called with the profile. 
```
mvn dependency:tree -Pscala-2.12,spark-3.0
```

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ spark-3.2-spline-agent-bundle_2.12 ---
[INFO] za.co.absa.spline.agent.spark:spark-3.2-spline-agent-bundle_2.12:jar:1.0.0-SNAPSHOT
[INFO] +- za.co.absa.spline.agent.spark:agent-core_2.12:jar:1.0.0-SNAPSHOT:compile
[INFO] |  +- org.scala-lang:scala-compiler:jar:2.12.15:provided
[INFO] |  +- za.co.absa.commons:commons_2.12:jar:1.2.0:compile
[INFO] |  +- org.apache.spark:spark-core_2.12:jar:2.4.8:provided
```

From this you can see the dependency is provided and should not have any influence further down the line.

But the bundle itself is **not supposed to be used as maven dependency** anyway. It is an artifact ready to use with the specific Spark and Scala version. So it doesn't really matter what it declares dependency on.

https://github.com/AbsaOSS/spline-spark-agent#selecting-artifact
