### ISSUE TITLE
Support for DELETE, UPDATE and MERGE in Delta

### ISSUE THREAD

**Issue by mohitgarg4628** [AbsaOSS/spline-spark-agent#517]
Hi,

We are using following code for capturing lineage
```python
from delta.tables import *
from pyspark.sql.functions import *

oldIncrementalData = spark.range(6).withColumn("name", lit("Dhruv"))
old_deltaTable = DeltaTable.forPath(spark, "/data/events_old/")

newIncrementalData = spark.range(5).withColumn("name", lit("Neha"))
```
# Create DeltaTable instances using the path of the Delta table
```python
deltaTable = DeltaTable.forPath(spark, "/data/events/")
```
# Execute Upsert
```python
(old_deltaTable
 .alias("oldData") 
 .merge(newIncrementalData.alias("newData"), "oldData.id = newData.id")
 .whenMatchedUpdate(set = {"name": col("newData.name")})
 .whenNotMatchedInsert(values = {"id": col("newData.id"), "name": col("newData.name")})
 .execute()
)
```

Here SplineQueryExecutionListener is not getting called for merge operation.
Can you please help for the same.
Thanks

**Comment by cerveada** [comment]
Python `merge` function is equivalent to `MERGE INTO` spark sql command

https://docs.databricks.com/spark/latest/spark-sql/language-manual/delta-merge-into.html

**Comment by mohitgarg4628** [comment]
@cerveada Can you please help for the same, how can we resolve this issue?

**Comment by cerveada** [comment]
Support for DELTE, UPDATE and MERGE in delta was not yet implemented, it will be added under this ticket.

**Comment by sh0ck-wave** [comment]
@cerveada @wajda Even with this feature, it will not capture the lineage when using the Python/Scala api, only for the sql MERGE command. For details please refer to https://github.com/delta-io/delta/issues/1521

**Comment by dishkakrauch** [comment]
> @cerveada @wajda Even with this feature, it will not capture the lineage when using the Python/Scala api, only for the sql MERGE command. For details please refer to [delta-io/delta#1521](https://github.com/delta-io/delta/issues/1521)

Hello there. Looks like all commits were done at delta side.
