### ISSUE TITLE
Get Notebook name of databricks 

### ISSUE THREAD

**Issue by zacayd** [AbsaOSS/spline-spark-agent#531]
Can we show in spline the name of the notebooks that run the execution plan?
Or is a rest-api for this?

**Comment by wajda** [comment]
If I remember correctly, you have to call a Databrics specific API (`dbutils`?) to get the notebook name. Things like that are not collected automatically, but you can use a post processing filter to capture it and store it as an extra property in the execution plan or event entity. 

In the development version there is a handy [MetadataCollectingFilter](https://github.com/AbsaOSS/spline-spark-agent/blob/develop/core/src/main/scala/za/co/absa/spline/harvester/postprocessing/metadata/MetadataCollectingFilter.scala) filter made specifically for this purpose.

You can find example of usage here:
- [MetadataCollectingFilterSpec.scala](https://github.com/AbsaOSS/spline-spark-agent/blob/develop/core/src/test/scala/za/co/absa/spline/harvester/postprocessing/extra/MetadataCollectingFilterSpec.scala)
- [SparkApp.scala#L42-L54](https://github.com/AbsaOSS/spline-spark-agent/blob/develop/examples/src/main/scala/za/co/absa/spline/SparkApp.scala#L42-L54)

In the 0.7 version you can use a custom [post processing filter](https://github.com/AbsaOSS/spline-spark-agent/tree/release/0.7#filters) to get what you want programmatically.

At the moment, there UI doesn't display extra properties, but the Consumer API returns extra properties of the execution plan entity: `/lineage-detailed?execId=${exec_plan_uuid}`

Note that the Consumer API is not stable and is a subject for change in the future versions.

**Comment by zacayd** [comment]
Question- how can i run on postman- rest api   aganist the Spline rest api

**Comment by wajda** [comment]
What do you mean? Spline REST API is just like any other REST API.

**Comment by zacayd** [comment]
yes but where can i find the documentation for this?
what actions can I do?

**Comment by wajda** [comment]
Open the index page of the Spline Gateway server in a browse (e.g. http://localhost:8080) and you'll see a status page that, among other information, contains links to Swagger definition for both Producer and Consumer REST API. Unfortunately we do not have any solid developer documentation about the structure of those API, but some basic info is available in those Swagger defs.

**Comment by zacayd** [comment]
HI
if you can  point me to a member of the comunity that succeeded to get the notebook name of databricks it will be great!
thanks in advance
Zacay
