### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by dk1844** [AbsaOSS/spline-spark-agent#536]
Having tried to run `tests` on Windows (Win 11 x64) with docker-desktop alternative running, I am failing to test-run the project.

I have run `mvn test > out.txt`, attaching a log
[out.zip](https://github.com/AbsaOSS/spline-spark-agent/files/10075978/out.zip)

@cerveada @miroslavpojer

**Comment by cerveada** [comment]
Does the build works without tests? 
```
mvn install -DskipTests
```

**Comment by dk1844** [comment]
> Does the build works without tests?
> 
> ```
> mvn install -DskipTests
> ```

That is fine.
```
[INFO] Spline Spark Agent ................................. SUCCESS [  1.068 s]
[INFO] agent-core_2.11 .................................... SUCCESS [ 44.893 s]
[INFO] examples_2.11 ...................................... SUCCESS [ 10.790 s]
[INFO] integration-tests_2.11 ............................. SUCCESS [ 37.010 s]
```

**Comment by miroslavpojer** [comment]
> mvn install -DskipTests

I can confirm that this command is working.
```
[INFO] Spline Spark Agent ................................. SUCCESS [  2.853 s]
[INFO] agent-core_2.11 .................................... SUCCESS [01:48 min]
[INFO] examples_2.11 ...................................... SUCCESS [ 27.231 s]
[INFO] integration-tests_2.11 ............................. SUCCESS [ 44.571 s]

```
[out_skipTest_after_checkout.zip](https://github.com/AbsaOSS/spline-spark-agent/files/10081723/out_skipTest_after_checkout.zip)

**Comment by miroslavpojer** [comment]
If I follow example from readme to build an agent for Spark 2.4 and Scala 2.12:

```
mvn scala-cross-build:change-version -Pscala-2.12
mvn install -Pscala-2.12,spark-2.4 -DskipTests
```
then output passed too:

```
[INFO] Spline Spark Agent ................................. SUCCESS [  2.700 s]
[INFO] agent-core_2.12 .................................... SUCCESS [01:22 min]
[INFO] examples_2.12 ...................................... SUCCESS [ 23.134 s]
[INFO] integration-tests_2.12 ............................. SUCCESS [ 37.750 s]
[INFO] spark-2.4-spline-agent-bundle_2.12 ................. SUCCESS [  4.566 s]
[INFO] spark-3.0-spline-agent-bundle_2.12 ................. SUCCESS [  5.109 s]
[INFO] spark-3.1-spline-agent-bundle_2.12 ................. SUCCESS [  3.399 s]
[INFO] spark-3.2-spline-agent-bundle_2.12 ................. SUCCESS [  6.487 s]
[INFO] spark-3.3-spline-agent-bundle_2.12 ................. SUCCESS [ 10.080 s]
```

**Comment by miroslavpojer** [comment]
Here is my build output when called command:
`mvn test -Pscala-2.12,spark-2.4`

```
[INFO] Spline Spark Agent ................................. SUCCESS [  4.477 s]
[INFO] agent-core_2.12 .................................... SUCCESS [01:03 min]
[INFO] examples_2.12 ...................................... SUCCESS [ 18.935 s]
[INFO] integration-tests_2.12 ............................. FAILURE [07:36 min]
[INFO] spark-2.4-spline-agent-bundle_2.12 ................. SKIPPED
[INFO] spark-3.0-spline-agent-bundle_2.12 ................. SKIPPED
[INFO] spark-3.1-spline-agent-bundle_2.12 ................. SKIPPED
[INFO] spark-3.2-spline-agent-bundle_2.12 ................. SKIPPED
[INFO] spark-3.3-spline-agent-bundle_2.12 ................. SKIPPED

```

[out_test_by_readme.zip](https://github.com/AbsaOSS/spline-spark-agent/files/10081913/out_test_by_readme.zip)

**Comment by cerveada** [comment]
Seems like most of them are:
```
org.apache.spark.sql.AnalysisException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient;
```
or different paths on windows like:
```
  "file:[/C:/Users/myuser/AppData/Local/Temp/]csv26950794154055502..." was not equal to "file:[C:\Users\myuser\AppData\Local\Temp\]csv26950794154055502..." (FileFormatSpec.scala:190)
```

That may be good news because it could be enough to fix these two issues to fix most of these tests.

**Comment by miroslavpojer** [comment]
> Seems like most of them are:
> 
> ```
> org.apache.spark.sql.AnalysisException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient;
> ```
> 
> or different paths on windows like:
> 
> ```
>   "file:[/C:/Users/myuser/AppData/Local/Temp/]csv26950794154055502..." was not equal to "file:[C:\Users\myuser\AppData\Local\Temp\]csv26950794154055502..." (FileFormatSpec.scala:190)
> ```
> 
> That may be good news because it could be enough to fix these two issues to fix most of these tests.

Windows paths could be solved by correct using URI vs Paths. I can do it.

**Comment by wajda** [comment]
Should we add one more dimension to our CI build config? - Win/Linux operating system? So we'll have SparkVer+ScalaVer+OS builds?

**Comment by miroslavpojer** [comment]
> Should we add one more dimension to our CI build config? - Win/Linux operating system? So we'll have SparkVer+ScalaVer+OS builds?

I guess no. From my research there is not expected end user with windows (except browsers running in windows.). Source of problem is my selection of windows machine in the middle of them living in Mac OS ecosystem. @Zejnilovic Do you agree?
