### ISSUE TITLE
spline- how to recognize if the both execution plans represents the same entity

### ISSUE THREAD

**Issue by zacayd** [AbsaOSS/spline-spark-agent#557]
Hi 
After investigation and running of spline- i found that each command that reads from persistent and  writes to persisnt is kept under execution plan
for example 

```python
spark.read\
    .option("header","true")\
    .option("inferschema","true")\
    .csv("/FileStore/tables/circuits-2.csv")\
    .write\
    .mode('overwrite')\
    .csv("/FileStore/tables/ind-2.csv")
```

Each time the spark code runs again- it generates a new exection plan (since it keeps history)
my question is -how can i identify that the  a serise of execution plans describes the same action?

**Comment by cerveada** [comment]
If you think about the case where the same plan is used multiple times with the same data sources, it should already create only one ExecutionPlan on the server. The Plan id is a hash of the plan itself, so two identical plans will have the same id. Problem is some small changes in the plan may cause them to become different.

See: https://github.com/AbsaOSS/spline/issues/893

If you are talking about identifying the same operation done on different data sources. That is more difficult. It would mean looking for graph Isomorphisms, comparing the graphs and checking for the same operations while ignoring the unimportant metadata.

Alternatively user could just tag their plans with some kind of id/name to identify the same jobs.

**Comment by zacayd** [comment]
1. I wrote this code it generated 2 execution plan
after ru running it again (with no change) - it generated more 2 and so on -each time
2. "Alternatively user could just tag their plans with some kind of id/name to identify the same jobs."- how can it be done?

3. here is the spark sample code:

```python
sc._jvm.za.co.absa.spline.harvester.SparkLineageInitializer.enableLineageTracking(spark._jsparkSession)

from pyspark.sql.functions import col
# File location and type
file_location = "/FileStore/tables/circuits-2.csv"
file_type = "csv"

# CSV options
infer_schema = "true"
first_row_is_header = "true"
delimiter = ","

spark.read\
    .option("header","true")\
    .option("inferschema","true")\
    .csv("/FileStore/tables/circuits-2.csv")\
    .write\
    .mode('overwrite')\
    .csv("/FileStore/tables/ind-2.csv")
    
df=spark.read\
    .option("header","true")\
    .option("inferschema","true")\
    .csv("/FileStore/tables/circuits-2.csv")

#df.printSchema()

df=df.withColumn("CXX", col("lat"))
df.createOrReplaceTempView("Data")
df1=spark.sql("select *from Data")
df1.write.mode("overwrite").csv("mycsv.csv")
```
