### ISSUE TITLE
Fix integration tests on Java 11

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/spline-spark-agent#576]

**Comment by cerveada** [comment]
From several issues it seems the full Java 11 support was only implemented in Spark 3.0.0.

https://issues.apache.org/jira/browse/SPARK-24417
https://stackoverflow.com/questions/49961991/java-lang-illegalargumentexception-at-org-apache-xbean-asm5-classreader-initu

**Comment by wajda** [comment]
Ah, silly me, I forgot that Spark < 3.0 required Java 1.8 :man_facepalming: 
I guess what we'll do instead is adding another pair of automated build configs on the TC, one per scala version, no tests, Java 11, purely for the purpose of producing build artifacts for occasional manual testing. The build configs would be similar to the existing "Auto deploy to Maven", but just without any deployment.
