### ISSUE TITLE
console and logging dispatcher are printing internal model instead of producer api json

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/spline-spark-agent#588]
- produce the same json as httpDispatcher
- make the version configurable

**Comment by wajda** [comment]
I understand it could be convenient for certain cases, but just wondering, is there any other specific use-case for which it is important? `console` and `logging` were added merely for logging/debugging purposes, they have never meant to produce output that could be used in production.

**Comment by cerveada** [comment]
viewing/testing Databricks output on rest of the Spline
