### ISSUE TITLE
ConfigurationConverter.getProperties is unable to hundle Integer type values from Yaml

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/spline-spark-agent#610]
For example:
```
spline.lineageDispatcher.kafka.producer.max.in.flight.requests.per.connection:1
```

This is fixed in commons-configuration:1.7 https://issues.apache.org/jira/browse/CONFIGURATION-432

Unfortunately, Spark 2.4 depends on version 1.6

There already were other issues with YAML as version 1.2 being interpreted as float and there may be more.
Other properties sources just treat everything as string and do the conversion once it is asked for. Maybe we could use Yaml the same way.

**Comment by cerveada** [comment]
Reported in #609

**Comment by cerveada** [comment]
Should we keep this open for future complete fix? Since #611 is only fixing the default, not removing the issue completely.

**Comment by wajda** [comment]
I'd like to propose a proper fix. Give me a sec.

**Comment by wajda** [comment]
Since the above PR is already merged, I'll move the rest part to a new issue.
