### ISSUE TITLE
Use external jar for shading json4s

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/spline-spark-agent#667]
Current solution of shaded json4s classes in project makes testing and debugging difficult. To solve this, shaded json4s will be moved to external jar/library.

**Comment by cerveada** [comment]
Maven Shade Plugin is having issues shading Scala classes
https://stackoverflow.com/questions/55309684/does-maven-shade-plugin-work-with-scala-classes
https://issues.apache.org/jira/browse/MSHADE-345

**Comment by cerveada** [comment]
http://eed3si9n.com/jarjar-abrams/

**Comment by cerveada** [comment]
This issue: https://github.com/eed3si9n/jarjar-abrams/issues/32 is causing an exception when instantiating shaded `org.json4s.DefaultFormats`

**Comment by wajda** [comment]
Closing this in favour of #675
