### ISSUE TITLE
Replace json4s by other json SerDe

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/spline-spark-agent#675]
Since json4s seems to be causing compatibility issues between different versions of Spark and shading, it seems to be difficult (see #667) it is worth considering to replace it by different library.

Ideal features of the library would be:
- Support for Scala 2.11, 2.12, 2.13
- Stable - Ideally a library that keeps each major release in a different package, [described here](https://github.com/rallyhealth/sbt-shading#chapter-3-a-solution-emerges)
- Automatic mapping of case classes to json

Some candidates:

https://github.com/spray/spray-json
no automapping

https://github.com/rallyhealth/weePickle
no automapping

**Comment by wajda** [comment]
ef674f44290f4670da88e0037b694995b2dd3c4f - A quick attempt to replace a shaded `Json4s` with a shaded `Jackson + Scala module`
