### ISSUE TITLE
Scala 2.13 support for Spark 3.3.x

### ISSUE THREAD

**Issue by d-m-h** [AbsaOSS/spline-spark-agent#735]
Hi - my org is currently using Spark 3.3.x for our new projects, and the version they're using is compiled with Scala 2.13.

Would it be possible for add Scala 2.13 support for the Spark 3.3.x series?

**Comment by wajda** [comment]
Duplicate for #717

@d-m-h, it's not an immediate priority for us at the moment, but I'll try to do it as soon as I have time.
