### ISSUE TITLE
BuildInfo.version reports 'null'

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#75]
Most likely a collision between 'build.properties' files from different JARs.

**Comment by cerveada** [comment]
Fix used in gateway: https://github.com/AbsaOSS/spline/commit/336b4a636ad5d343b01673a4bc4dc7be3edbe315#diff-aa5607a2c784368e17340bfa6903c66a

**Comment by DaimonPl** [comment]
It looks like it completely breakes lineage reporting in my setup. Is it possible to fix it in spline 0.5.x ?
