### ISSUE TITLE
Spline Agent required for spark 3.4 version and Scala 2.12 

### ISSUE THREAD

**Issue by B09306** [AbsaOSS/spline-spark-agent#764]
Hi Team,
Now everyone is moving from spark 3.3 to spark 3.4 and for that spark 3.4 we don't have spark agent .
so we are not able to install spline on Databricks cluster whose spark version is 3.4 
when can we  expect release of spline agent for Spark 3.4.1 and Scala 2.12 ?
this is urgent for us please do reply as soon as possible

**Comment by justvinhhere** [comment]
same situation here, we wanna move to spark 3.5 but it seems Spline agent did not support it.

**Comment by wajda** [comment]
Please refer issue #705
