### ISSUE TITLE
Support for spark 3.5

### ISSUE THREAD

**Issue by igreenfield** [AbsaOSS/spline-spark-agent#770]
Can you add support for spark 3.5.X

**Comment by wajda** [comment]
Sure, right after #705 I guess. Unfortunately the team is at zero capacity at the moment. Hoping for community help.

**Comment by dishkakrauch** [comment]
Hello there. Will you add support of spark 3.5.x this?

**Comment by wajda** [comment]
I can give it a quick try. But if there are braking changes that need to be addressed I hardly likely to be able to find time for this till the end of the year. Any help/PR is appreciated of course. Let me try and see.

**Comment by wajda** [comment]
@igreenfield, @dishkakrauch I've created a [PR](#826). The integration tests passed, but I didn't test it with any real Spark setup. Can you test it if works in your real-life cases please?

You can download the agent bundles here:
- Scala 2.11 - https://teamcity.jetbrains.com/buildConfiguration/OpenSourceProjects_AbsaOSS_SplineAgentSpark_AutoBuildArtifactsSparkScala211/4763292?buildTab=artifacts
- Scala 2.12 - https://teamcity.jetbrains.com/buildConfiguration/OpenSourceProjects_AbsaOSS_SplineAgentSpark_AutoBuildArtifactsSparkScala212/4763294?buildTab=artifacts

**Comment by dishkakrauch** [comment]
> @igreenfield, @dishkakrauch I've created a [PR](#826). The integration tests passed, but I didn't test it with any real Spark setup. Can you test it if works in your real-life cases please?
> 
> You can download the agent bundles here:
> 
> * Scala 2.11 - https://teamcity.jetbrains.com/buildConfiguration/OpenSourceProjects_AbsaOSS_SplineAgentSpark_AutoBuildArtifactsSparkScala211/4763292?buildTab=artifacts
> * Scala 2.12 - https://teamcity.jetbrains.com/buildConfiguration/OpenSourceProjects_AbsaOSS_SplineAgentSpark_AutoBuildArtifactsSparkScala212/4763294?buildTab=artifacts

Sure, why not.

**Comment by dishkakrauch** [comment]
It's worked. Thank you.
