### ISSUE TITLE
Customized Listener

### ISSUE THREAD

**Issue by lantse** [AbsaOSS/spline-spark-agent#799]
### Discussed in https://github.com/AbsaOSS/spline-spark-agent/discussions/798

<div type='discussions-op-text'>

<sup>Originally posted by **lantse** March 28, 2024</sup>
We are using mappartition function in Spark to transform data in batch. The data read()/write() for each record are in a user defined adapter class. Is there a way to let the spline spark agent to `listen` to the write() function so that this specific transformation would not be missing in the data lineage record?

In another word, how do we supplement or add to the data lineage record for the area that the agent cannot collect by default? Thanks.</div>

**Comment by wajda** [comment]
please do not duplicate messages in discussions and issues.
