### ISSUE TITLE
Add Table Catalog params for non hive tables

### ISSUE THREAD

**Issue by radford1** [AbsaOSS/spline-spark-agent#83]
When spark is using a hive metastore and the table type is using parquet instead of hive then the table catalog params are not populated.

**Comment by DaimonPl** [comment]
Looks like i had same issue but thought that cause was different: https://github.com/AbsaOSS/spline/issues/685

**Comment by radford1** [comment]
Ah got ya. I'm working on a fix that I'm getting ready to push that will add these to the params the same way hive tables work. Hopefully this will also help to solve your issue as well.

**Comment by DaimonPl** [comment]
@wajda any chance to have 0.5.3 released soon? I'd like to deploy spark agents for 3 teams and check how everything is working - so far 0.5.2 would fail quite fast

**Comment by wajda** [comment]
The release procedure started - https://teamcity.jetbrains.com/buildConfiguration/OpenSourceProjects_AbsaOSS_SplineAgentSpark_Release?mode=builds

**Comment by wajda** [comment]
done
