### ISSUE TITLE
Spline does not display schema/database for Hive tables

### ISSUE THREAD

**Issue by DaimonPl** [AbsaOSS/spline-spark-agent#85]
Hive supports multiple schema/databases for example `my_db.my_table`, `different_team_db.my_table`

Spline correctly recognizes URI for both but UI only displays `my_table`. Database/Schema `my_db` is very crucial and it would benefit everyone to also display database/schema in lineage - or maybe just full table name like `my_db.my_table` ?

**Comment by wajda** [comment]
possible duplicate for #83

**Comment by DaimonPl** [comment]
@wajda it looks that after @radford1 fix databse is proeprly reported to spline backend, but UI still does not display database name on graph

**Comment by DaimonPl** [comment]
So probably this issue could be reopened in spline project

**Comment by wajda** [comment]
No worries, it will be handled in the scope of another task - https://github.com/AbsaOSS/spline/issues/645#issuecomment-635901189
